### ISSUE TITLE
Unminified version of js file

### ISSUE THREAD

**Issue by pallavsipani** [joni2back/angular-filemanager#10]
I am trying to build upon your project. Please provide the expanded version of angular-filemanager.min.js. The minified version is a little cryptic to understand whats going on. Thanks.

**Comment by joni2back** [comment]
Hello, you can use the commented source instead using the minified file..
https://github.com/joni2back/angular-filemanager/blob/master/index.html
```html
    <script src="assets/js/app.js"></script>
    <script src="assets/js/config.js"></script>
    <script src="assets/js/chmod.js"></script>
    <script src="assets/js/item.js"></script>
    <script src="assets/js/filenavigator.js"></script>
    <script src="assets/js/fileuploader.js"></script>
    <script src="assets/js/translations.js"></script>
    <script src="assets/js/controller.js"></script>
    <script src="assets/js/selector-controller.js"></script>
```
instead
```html
<script src="assets/js/angular-filemanager.min.js"></script><!-- Using minified file -->
```
---------------
I just updated [bash.sh](https://github.com/joni2back/angular-filemanager/blob/master/build.sh) to pass parameters, so now you can do:
```bash
jonas@:~/www/angular-filemanager$bash build.sh --prevent-build
OUTFILE: assets/js/angular-filemanager.min.js
```

**Comment by pallavsipani** [comment]
Great. Thanks a lot :)

**Comment by joni2back** [comment]
:+1:
