### ISSUE TITLE
Modals not working

### ISSUE THREAD

**Issue by fkoester** [joni2back/angular-filemanager#101]
First I want to say that your angular-filemanager is awesome! I really like it and it helps to implement my project to create a simple web app for securely sharing files via HTTP and a web interface.

So I successfully integrated the view into my Angular web app, but using the latest git version the modals are not working any more when clicking on the navbar buttons (e.g. upload).

I tried to debug this issue yesterday but I could not find the reason for this. I assume it is maybe some kind of conflict between Angular and jQuery?

I will investigate this issue further today but wanted to document it if someone else also hits this problem.

Any suggestions will be greatly appreciated!

**Comment by joni2back** [comment]
Hi @fkoester !! Thank you very much!!

I just cloned and tested the ***master*** branch and modals is working for me...
Can you please tell me if you have any changes (or working in a different branch)?

Also, check if jquery is included and paste here if there are any error in your js console.

Thanks!!

**Comment by fkoester** [comment]
Thanks @joni2back for your quick help! You were right, I didn't load jQuery in my project. Now everything is working as expected :-)
