### ISSUE TITLE
angular-translate: No sanitization strategy

### ISSUE THREAD

**Issue by fkoester** [joni2back/angular-filemanager#104]
Angular-translate logs a warning:

"pascalprecht.translate.$translateSanitization: No sanitization strategy has been configured. This can have serious security implications. See http://angular-translate.github.io/docs/#/guide/19_security for details."

Should probably be fixed.

**Comment by joni2back** [comment]
Thanks, this error is related to dependencies updates. I just fixed it (momentarily we use a null strategy to evaluate if is necessary to include ngSanitize)
