### ISSUE TITLE
How to set the root FTP path?

### ISSUE THREAD

**Issue by eladcandroid** [joni2back/angular-filemanager#109]

**Comment by joni2back** [comment]
Hi @eladcandroid you can create an FTP account in a specified folder.
But if you wait a few days, there will be the release of the new **angular-filemanager** version with the new api (multiple file support) that will allows that!!

**Comment by dnichols178** [comment]
I am using version 5.0, but I am unsure where I need to specify the directory I want to pull files from. Also, I have received bridge errors - it is not clear if /php/php-classic/ftp.php is supposed to be used or not. 

I notice a few lines in handler.php for the connection string, but there is also the:

`require_once __DIR__ . '/php-classic/src/autoloader.php';`

`use PHPClassic\ExceptionCatcher;`
`use PHPClassic\Ftp;`

I have tested multiple configurations and continue to have errors.

**Comment by durasj** [comment]
If you don't need FTP try my local bridge https://github.com/joni2back/angular-filemanager/pull/124

**Comment by dnichols178** [comment]
I will give it a try, but Is there no way to point the FTP connection to a directory on the server?

i.e. FTP server: domain.com/ Directory: domain.com/files.

My default FTP account points to my root and I can't change it.

**Comment by durasj** [comment]
You have to ask @joni2back as he is, I think, the author of that bridge. But if I remember correctly he said it is just example how to implement API and you could do your own bridge if you know any backend language (JS, Ruby, Python...)
