### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by joshmanders** [joni2back/angular-filemanager#116]

**Comment by joni2back** [comment]
@joshmanders sorry bro, removed !

**Comment by joshmanders** [comment]
https://github.com/joni2back/angular-filemanager/issues/59

This is not your first time. Retitling the issue and deleting the body isn't going to make this go away. I have reverted your deletions and will report you for spam if you continue to do this.

**Comment by Qix-** [comment]
Stahhhhhp doing this.
