### ISSUE TITLE
Clumsy UI. It's has very few common things with material design. 

### ISSUE THREAD

**Issue by AlexanderKozhevin** [joni2back/angular-filemanager#117]
Here is a good examples. 
![components_bottomsheets_modal15](https://cloud.githubusercontent.com/assets/4464561/13328721/4bce1e80-dc01-11e5-916f-8e00a9685ec6.png)
![files-app-01_2x 1](https://cloud.githubusercontent.com/assets/4464561/13328723/4c8d11b4-dc01-11e5-922f-f7527d7d821a.png)

**Comment by jlamer** [comment]
I think @joni2back welcomes any pull-requests :)

**Comment by joni2back** [comment]
Hi @AlexanderKozhevin we are using a bootstrap based material design styles. 
I'm aware that this bootstrap-skin is not the best approach to represent strict material-design, but we are working to improve this, on every feature every day.
Don't forget to give us a star :star: !! Thank you!

**Comment by joni2back** [comment]
Hi @AlexanderKozhevin take a look to the new changes, now follows some more material design rules.
@durasj Take a look you too :+1:

**Comment by durasj** [comment]
Hey, that looks promising. I would like to improve it a little bit more in the future but I am just too busy atm. Good work!
