### ISSUE TITLE
Use filemanager to pick files in tinyMCE, CKeditor etc

### ISSUE THREAD

**Issue by durasj** [joni2back/angular-filemanager#120]
I think the best way would be to add option to config where dev could add a callback which will be (if defined) called on every doubleclick instead of edit/preview etc with file path as argument.

I will implement this myself later today or tommorow but I want to hear your opinion or ideas.

**Comment by joni2back** [comment]
I will working on this feature... to enable an option that allows only-select file(s) for file selectors in other apps..
callbacks should be the right way

**Comment by jlamer** [comment]
Here is my implementation: https://github.com/jlamer/angular-filemanager/commit/52baaa64659379c8356844febe7290972ac85549

I am now using it on one of my websites.

**Comment by durasj** [comment]
I updated my implementation: https://github.com/durasj/angular-filemanager/tree/pick-file-callback ... anything missing @joni2back ?

**Comment by joni2back** [comment]
You now will need to extend the config doing something like

```js
angular.module('FileManagerApp').config(['fileManagerConfigProvider', function (config) {
  var defaults = config.$get();
  config.set({
    pickCallback: function(item) {
      var msg = 'Picked %s "%s" for external use'
        .replace('%s', item.type)
        .replace('%s', item.fullPath());
      window.alert(msg);
      copy.to.clipboard(item.fullPath())
      window.close();
    },

    allowedActions: angular.extend(defaults.allowedActions, {
      pickFiles: true,
      pickFolders: false,
    }),
  });
}]);

**Comment by durasj** [comment]
Could you also think about implementing https://github.com/durasj/angular-filemanager/commit/67117561157ecc9c6da143f4f7aba808f3dcdceb? So I can return true from callback when I don't need to pick any file and manager will work as usual. Or something like that.

I am using it like that to pick files using TinyMCE, but sometimes I open file manager without the intention to pick file and so my callback will return false and manager works fine and I don't have to unset callback after picking.

**Comment by joni2back** [comment]
Great approach @durasj, would you like to create a PR for that?
(don't forget to use curly braces in conditionals please :angel:)

Note: Maybe follow the behaviour of ```return false``` will be better option (like event bindings example click onclick="function() {return false}" will stop execution)
```js
var endCallback = $scope.config.pickFileCallback(item.model);
if (endCallback === false) {
    return;
}

but I leave it to your liking

**Comment by joni2back** [comment]
Already merged you proposal

**Comment by durasj** [comment]
Really sorry about curly braces. Thanks for accepting the changes. I was also thinking about using false but true seemed more natural to me. Like var callbackDidSomething = true and false if it did not so the smart click can continue.
