### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Dexter990** [joni2back/angular-filemanager#121]
Hello everyone. I have spring mvc application and I want to implement filemanager inside my application. When user goes to documentation.jsp i want that application runs on that page. I included javascript files,and everything looks fine,but i don't know how to write servlet code for it to make it work..I hope you understand me. 

Best wishes!

**Comment by jlamer** [comment]
Hey, there is java servlet which could help you: https://github.com/joni2back/angular-filemanager/tree/master/bridges/java

**Comment by joni2back** [comment]
Hey @Dexter990 there are another bridge https://github.com/joni2back/angular-filemanager/pull/95

**Comment by marcoserafini2** [comment]
Hi @Dexter990, I created a bridge written with Spring (integrating the java code already present in this repo), you find it [here](https://github.com/marcoserafini2/angular-filemanager-spring-bridge)
