### ISSUE TITLE
Don't use request body to download multiple files using GET

### ISSUE THREAD

**Issue by durasj** [joni2back/angular-filemanager#122]
It's not good idea to use request body when using GET HTTP method.

More info: http://stackoverflow.com/questions/978061/http-get-with-request-body and https://tools.ietf.org/html/rfc2616#section-4.3

I would advise to use query parameters like: `?path[]=/public_html/image.jpg&path[]=/public_html/image2.jpg`

It would be wise to use one URL and action for both single and multiple file downloads. Backend should check wheter one or more paths were send. AFAIK PHP and Express (node.js) will automatically turn more parameters (with the name like I mentioned before) to array.

**Comment by joni2back** [comment]
Yes, I know that is unsafe and not the right way. 
There are a lot of current browsers without support of ``window.saveAs`` (to download by ajax), 
So for the moment we are using GET request to open it in another window. Maybe will be a better approach like using a post method html form... Ill be take care with this..

**Comment by durasj** [comment]
I think it's completely OK to use GET, but I would like to have paths sent as array in one request in query parameters like that:
