### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by joni2back** [joni2back/angular-filemanager#130]
Improve template for display the name of the selected files
![angular filemanager](https://cloud.githubusercontent.com/assets/2049935/14095458/ecb5c08e-f536-11e5-913e-0b9d13427590.png)

Add some translations like this
![angular filemanager2](https://cloud.githubusercontent.com/assets/2049935/14095459/ecdb05ba-f536-11e5-92f1-f60d89a96219.png)

**Comment by joni2back** [comment]
Hi @durasj would be nice if you have time to help me with this one !! Regards

**Comment by durasj** [comment]
I will take a look in the next days. Maybe over the weekend.

**Comment by joni2back** [comment]
Can I close this one?

**Comment by durasj** [comment]
I guess :) Anything else to fix?

**Comment by joni2back** [comment]
This is also covered?? 
![angular filemanager](https://cloud.githubusercontent.com/assets/2049935/14095458/ecb5c08e-f536-11e5-913e-0b9d13427590.png)
I thinking in improve or redesign this behaviour... ideas?
