### ISSUE TITLE
Styling "file upload"

### ISSUE THREAD

**Issue by dnichols178** [joni2back/angular-filemanager#132]
Using the file manager on Chrome I wanted to get rid of "no file chosen" when uploading files.

To create an upload "area" simply remove (or comment) out a line in modal.html template and add the lines below.

`<input type="file" title=" " class="form-control" ng-file="$parent.uploadFileList" multiple="multiple">`

And add the following lines in its place:

`<div class="area">`
`<div class="dropZone">`
`<span class="add">Add Files to Upload</span><input type="file" class="form-control" multiple>`
`</div>`
`</div>`

Now add the following lines to the dialogs.css file:

`.area {
  width: 100%;
  padding: 15px;
}

.dropZone {
  border: 5px dashed #bbb;
  -webkit-border-radius: 5px;
  border-radius: 5px;
  padding: 50px;
  padding-bottom:0px;
  text-align: center;
  font: 21pt bold arial;
  color: #bbb;
  font-weight:bold;
  font-family:Arial;
}
.add {
  width:45em;
}

input[type='file'] {
    top:-45px;
    height:50px;
    position:relative;  
    width:100%;
    opacity:0
}`

The result should be similar to the screenshot:

![screen-shot](https://cloud.githubusercontent.com/assets/6627120/14505216/d416a9dc-017d-11e6-8dbc-0ebac2b408b0.png)

If a drag and drop feature is ever added this markup could be easily adapted.

**Comment by joni2back** [comment]
Thanks, i will test it to add to the project.

For your information, there are a hack for input[type=file]
that consists in trigger this click ... clicking other element... instead tricking with css

for example
```html
<button class="trigger">Click here to select files</button>
<input type="file" id="file" style="display:none">
$(".trigger").on("click", function() {
  $("#file").click();
});
```

**Comment by durasj** [comment]
I already did much better integration of ng-file-upload with support for drop, feedback when dropping and list of files which will be uploaded. You can see it here: https://github.com/durasj/angular-filemanager/tree/file-upload-v2

**Comment by durasj** [comment]
![file upload v2 demo](https://cloud.githubusercontent.com/assets/1062898/14507153/add384e0-01c1-11e6-9b5a-84c51e89e2d3.gif)

**Comment by dnichols178** [comment]
durasj - I implemented your code last night, but in Chrome (version 49.0.2623.112) the "select files" button doesn't bring up a dialog to select files and automatically starts an upload.

**Comment by joni2back** [comment]
@durasj could you propose a clean MR with the changes of that screenshot??

**Comment by durasj** [comment]
I already did: https://github.com/joni2back/angular-filemanager/pull/118 but it was declined.

@dnichols178 will take a look later at those issues

**Comment by durasj** [comment]
@dnichols178 I just tried it and it works completely like it should ... I could not reproduce the issues you mentioned.

**Comment by joni2back** [comment]
Hi @durasj this was merged... there are a problem when you drag items in the app (not out from browser)... it show the overlay like if you are dragging a real file

**Comment by durasj** [comment]
Thanks, I will look at it

--
S pozdravom

Jakub Ďuraš
Web developer, D.Media, s.r.o.
m: +421 917 432 974
e: jakub@duras.me [mailto:jakub@duras.me]
w: www.duras.me [http://duras.me/]
On 18. 4. 2016 15:39:54, Jonas Sciangula Street <notifications@github.com> wrote:
Hi @durasj [https://github.com/durasj] this was merged... there are a problem when you drag items in the app (not out from browser)... it show the overlay like if you are dragging a real file
