### ISSUE TITLE
Root Path

### ISSUE THREAD

**Issue by Lasim** [joni2back/angular-filemanager#135]
Dear angular-filemanager community,

how and where can I set the "root path" ?

For example angular-filemanager is installed in path /vaw/www/angular and I want to edit files
under the path /srv/xyz ?

(Without creating symlink... )

Regards,
Lasim

**Comment by durasj** [comment]
Hey,

what bridge are you using?

**Comment by Lasim** [comment]
Hi durasj,

what bridge can or should I use to do that ;-)))) ??

Thank you

**Comment by durasj** [comment]
Depends on which language you are running on your backend.

I made [php-local bridge](https://github.com/joni2back/angular-filemanager/tree/master/bridges/php-local) written in, well, php :)

You can set path that will be used in [index.php](https://github.com/joni2back/angular-filemanager/blob/master/bridges/php-local/index.php).

To use my bridge just point all actions in config to directory with my bridge.

**Comment by Lasim** [comment]
Like this:

`$fileManagerApi = new FileManagerApi(
['path' => '/srv/xyz']
);`


?

**Comment by durasj** [comment]
Just string 

`$fileManagerApi = new FileManagerApi('/srv/xyz');`

**Comment by Lasim** [comment]
Thank you!

**Comment by durasj** [comment]
Glad it worked :+1:

**Comment by ibnYusrat** [comment]
you rock!
