### ISSUE TITLE
PHP CLASSIC Missing

### ISSUE THREAD

**Issue by LordApo** [joni2back/angular-filemanager#139]
The php-classic folder is empty when downloaded, we need to manually add this https://github.com/joni2back/php-classic/tree/e0a6e78e78910f6848b3a5316fe231004d8cdbe6 # #

**Comment by joni2back** [comment]
Hi, you need to clone the project with submodules, for example

```git clone https://github.com/joni2back/angular-filemanager.git --recursive```
