### ISSUE TITLE
Update the API document

### ISSUE THREAD

**Issue by diego-XA** [joni2back/angular-filemanager#141]
The API document should be updated with the new API specification.

**Comment by joni2back** [comment]
Hi @diego-XA, It seems to have been github server repos error on that day... Now is ok... 

https://github.com/joni2back/angular-filemanager/blob/master/API.md

**Comment by diego-XA** [comment]
Actually, I am writing a backend in python and I am seeing that the front end sends the requests in the form:

`{
   "params":{
       .....
    }
}`

Also "rename" seems to be using "path" and "newPath" not "item" and "newItemPath". 
I also did not see any call to "move", only to rename. I think there are more things over there.

When I saw something related to APIv2 I thought that simply the docs were not updated.

**Comment by joni2back** [comment]
Seems that you are not updated the project
Try to git pull or download the master repo and tell me

**Comment by joni2back** [comment]
Check with online fresh project

Rename action in http://angular-filemanager.zendelsolutions.com/ is requesting with:
```json
{
    "action":"rename",
    "item":"/PARTICPANTES/pageHea6uuage_es_ES.jpg",
    "newItemPath":"/PARTICPANTES/pageHea6uuage_es_ESXXX.jpg"
}```

**Comment by diego-XA** [comment]
Right, I was using the last release instead of the code from the repository.

Thank you for taking your time clarifying this !
