### ISSUE TITLE
Error copying files with the last dist files

### ISSUE THREAD

**Issue by diego-XA** [joni2back/angular-filemanager#143]
I am using the last dist files to write a backend and when I am trying to copy a file inside the same directory ( for example `test.txt` to `test.txt.bkp` ), angular-filemanager is sending this:

```javascript
{
    action:  "copy",
    items: [ "test.txt" ],
    newPath: "/"
}
```
when it should send:

```javascript
{
    action:  "copy",
    items: [ "test.txt" ],
    newPath: "/test.txt.bkp"
}
```
NOTE: In the modal, **Destination** still shows `/test.txt.bkp`

**Comment by diego-XA** [comment]
I've checked the [demo site](http://angular-filemanager.zendelsolutions.com/) and it does exactly the same: the `newPath` is set to a directory name despite the new name assigned to the file.

In my humble opinion, there would be 2 ways to do this:

1. Only allow directories as destination in the frontend when several files are selected (this is how it works now) and when a single file is selected send together the new path with the new file name as sugested in my previous post.

2. Always send the new path with the new file name despite several source files were selected and let the backend handle this. The backend could throw an error in case destiny is not a directory and several source files were selected or do whatever it wants (like overwritting files).

I think that the first option is much better as it will be more efficient, but it also requires more work in the frontend.

**Comment by joni2back** [comment]
Hi, this is a bug in the js side..
When you select just one item you can give it a new name.. (but im saw is not sending in the request)
But when you select more than one, you only could select a folder (this is only that are working)

Let me write a fix and i will linking the commit to this issue

**Comment by diego-XA** [comment]
That would be great, thank you!

**Comment by joni2back** [comment]
Hi @diego-XA take a look to 3e36c1c that closes this one..
Now when you are copying a single file you will receive ```singleFilename``` param

For more info check the updated API
