### ISSUE TITLE
Java Bridge Possible Security Issue

### ISSUE THREAD

**Issue by szdmr** [joni2back/angular-filemanager#144]
The java servlet code takes the path variable directly and there is no check if it goes to parent folders. It is not possible with the module itself, but one can mimic the XHR's easily with paths starting with "../../../../../../" and end up downloading/listing all the files in the hard drive, depending on given access.

I know its the minimum code to make it work, but I am also sure that there will be people who copy paste most of the code from the example.

**Comment by joni2back** [comment]
Hi @szdmr thank you for this security report. 
Currently java bridge is obsolete regarding the new api spec.. But I will take into account for future modifications.

Regards!!
