### ISSUE TITLE
Copy link feature

### ISSUE THREAD

**Issue by datlong1502** [joni2back/angular-filemanager#145]
This module should support copy link of file.
example. with a file avatar.jpg it show option copyLink. After that file URL copied to clipboard and also support config callback for 3rd.

**Comment by joni2back** [comment]
Hi, thanks for recomend that feature, actually there are another issue like this #120 
I'll be working for that!! Regards

**Comment by durasj** [comment]
Hi, yep, as @joni2back said, I had probably same requirement. What do you think about my implementation?

**Comment by joni2back** [comment]
Hi @durasj let me check

**Comment by joni2back** [comment]
Hi @datlong1502 is supported now!! dd63d4e6d3f8b10fcf19a484a720d9d662289d1e
Thank you @durasj for your previous contribution!!

**Comment by joni2back** [comment]
You now will need to extend the config doing something like

```js
angular.module('FileManagerApp').config(['fileManagerConfigProvider', function (config) {
  var defaults = config.$get();
  config.set({
    pickCallback: function(item) {
      var msg = 'Picked %s "%s" for external use'
        .replace('%s', item.type)
        .replace('%s', item.fullPath());
      window.alert(msg);
      copy.to.clipboard(item.fullPath())
      window.close();
    },

    allowedActions: angular.extend(defaults.allowedActions, {
      pickFiles: true,
      pickFolders: false,
    }),
  });
}]);

**Comment by datlong1502** [comment]
Best work @joni2back , @durasj :+1:
