### ISSUE TITLE
image thumbnails

### ISSUE THREAD

**Issue by azerafati** [joni2back/angular-filemanager#147]
I would definitely love to see image thumbnails also embedded in the project. It would be awesome

**Comment by joni2back** [comment]
Hi @azerafati are you referring to thumbnails for image files?
how do u think? replacing icons??

Regards

**Comment by azerafati** [comment]
yea, it would be great to see small versions on the images instead a of their icon so to find them more easily. I really enjoyed this work and plan to use it in one of my projects, so I guess I can work on that part. I'll give it a try

**Comment by joni2back** [comment]
Great, Also I think about doing something like
https://codepen.io/tevko/pen/DdsnK

Or just use css class as extension, for example like this one:
https://gist.github.com/gschoppe/08a814043da5e5f02f5c#file-file-format-icons-css

**Comment by azerafati** [comment]
wow the second one was so clever, but for images really a thumbnail would be so much better

**Comment by joni2back** [comment]
@azerafati I just added file extension in icons for the moment.. You can check in http://angular-filemanager.zendelsolutions.com/ (large icon view)

**Comment by azerafati** [comment]
@joni2back no that commit doesn't resolve this. Those Icons are awesome but I meant image thumbnails. That's totally necessary too
 like this,
http://ckeditor.com/apps/ckfinder/3.3.0/ckfinder.html?Type=Images&CKEditor=editor1&CKEditorFuncNum=0&langCode=en

**Comment by jbabaei** [comment]
@joni2back i need this feature too.

plz reopen this issue and help us

**Comment by benfarhner** [comment]
@joni2back I would also love to see thumbnails supported natively in this project.

**Comment by morteza-gho** [comment]
I add images thumbnails:

           <div class="item-icon">

               <i class="glyphicon glyphicon-folder-open" ng-if="item.model.type === 'dir'"></i>

               <i class="glyphicon glyphicon-file" data-ext="{{ item.model.name | fileExtension }}"
                  ng-if="item.model.type === 'file' && !item.isImage()"
                  ng-class="{'item-extension': config.showExtensionIcons}"></i>

               <img ng-if="item.isImage()" ng-src="{{item.model.fullPath()}}" alt="">

            </div>
