### ISSUE TITLE
Can we implement this feature using angular2 RC1?

### ISSUE THREAD

**Issue by sachendrapal** [joni2back/angular-filemanager#149]
I am working on a project where i need to develop a module to manage files and folders and this application is perfectly doing it. 
Now i need some advice from you to how i can implement this same functionality using angular2 RC1. Just few tweaks to your application would help me a lot.

**Comment by durasj** [comment]
Hello, 

angular2 is quite different with components etc and I think it would require substantial rewrite.

Maybe you could make use of [ngUpgrade](https://www.google.sk/search?q=UpgradeAdapter).

But I am still interested what @joni2back thinks.

**Comment by joni2back** [comment]
Hi @sachendrapal for the moment, we arent going to migrate to angular2.
I prefer to continue with angular 1 while angular2 gets really polishing and stable

**Comment by sachendrapal** [comment]
@joni2back Thanks for your reply. But please let me know what can be done to migrate your project to angular2 because we have already started building our product on angular2.
Awaiting positive reply.
