### ISSUE TITLE
Select file

### ISSUE THREAD

**Issue by OnlyJCash** [joni2back/angular-filemanager#15]
Hi everyone,

is it possible to select a file in folder?
is it possible to get a file selected in folder to do another action?

Thanks
Best regards

Michele

**Comment by joni2back** [comment]
Hello how are you?
I cannot understand what are you want to do with the file manager.
Can you describe with more details the action you want to do?

Regards.

**Comment by OnlyJCash** [comment]
Hi,

Scenario example: i'm editing a news entity in my CMS. News entity has a Set of String containing a relative path to document (image or other). So, through CMS UI and file manager i should be able to select single or multiple image to associate a news entity (Possible action after select a document in filemanager).

Thanks
Best regards

Michele

**Comment by joni2back** [comment]
Do you want to select several files from a folder to copy or move to another folder?

**Comment by OnlyJCash** [comment]
More or less...

After selection, on press a custom button, will be call a custom function

function customFunction(data){
// do something
}

data is an array of object 
{
  name: 'Image A',
  path: '/folder_1/folder_child/image_a.png',
  size: #### ,
 // other metadata information
}

Is it possible?

Thanks
Best regards
Michele

**Comment by joni2back** [comment]
Actually, there are a variable named **temp** that stores the selected item
```js
 $scope.temp = new Item();
```
Your idea is to handle multiple temps (selected) items, so we need to refactor to
```js
 $scope.temps = [];
```
And all the item-related methods of the controller to could handle selected files.

This feature is a nice to have, but wont be implemented in the nexts releases.
If you want, you can do a refactor an propose with a pull request.

Regards
