### ISSUE TITLE
Getting Bridge Response Error

### ISSUE THREAD

**Issue by sachendrapal** [joni2back/angular-filemanager#152]
I have downloaded the Zip file and trying to run it locally but getting Bridge Response Error. Do i need to setup database locally? If yes then how.
![image](https://cloud.githubusercontent.com/assets/19491130/15789368/5f5fa2ee-29e9-11e6-87b5-88c15a1024b9.png)

Waiting for a positive reply.

**Comment by LordApo** [comment]
No, you need to `git clone https://github.com/joni2back/angular-filemanager.git --recursive`

**Comment by sachendrapal** [comment]
@LordApo  i have done the same but still getting the same error. Are there other config files i need to manage?

**Comment by joni2back** [comment]
Hi @sachendrapal after you clone repo with the php-classic sources, did you modify the handler.php file to set your own ftp credentials??

Regards!
PD: Thanks @LordApo

**Comment by sachendrapal** [comment]
I am trying to run it locally so i think there is no need to set the ftp credentials. Am i right?
Also i have edited the config file like,
 listUrl: 'bridges/php-local/',
            uploadUrl: 'bridges/php-local/',
            renameUrl: 'bridges/php-local/',
            copyUrl: 'bridges/php-local/',
            moveUrl: 'bridges/php-local/',
            removeUrl: 'bridges/php-local/',
            editUrl: 'bridges/php-local/',
            getContentUrl: 'bridges/php-local/',
            createFolderUrl: 'bridges/php-local/',
            downloadFileUrl: 'bridges/php-local/',
            downloadMultipleUrl: 'bridges/php-local/',
            compressUrl: 'bridges/php-local/',
            extractUrl: 'bridges/php-local/',
            permissionsUrl: 'bridges/php-local/'

Is there any other settings i need to do as well?

**Comment by durasj** [comment]
I think you need to set files directory https://github.com/joni2back/angular-filemanager/blob/master/bridges/php-local/index.php#L16 ... Something like
`$fileManagerApi = new FileManagerApi("../files");`

**Comment by sachendrapal** [comment]
I have something like this but still getting the error,

$fileManagerApi = new FileManagerApi("C:/Users/Sachendra Pal/Documents/Genieji/Angular/Github/New folder/angular-filemanager", 'en');

Am i missing anything?

**Comment by durasj** [comment]
What's the error you are getting?

**Comment by sachendrapal** [comment]
In browser console i am getting error 405: Method not allowed under handler.php file.

**Comment by sachendrapal** [comment]
@durasj Thanks for your valuable time. Its working perfectly fine. Closing the issue.

**Comment by durasj** [comment]
@sachendrapal No problem, glad I could help!

**Comment by joni2back** [comment]
Thanks @durasj !

**Comment by itdotnet** [comment]
hi
I also have a problem.  I have the following error
Error 405 - Bridge response error, please check the API docs or this ajax response

In your opinion, what's the problem?!

**Comment by jrondorf** [comment]
Check FileManagerApi class. This class can be initialized with additional logging. 
Then, check your browsers dev tools, and the message when the local bridge PHP handler is called (network tab).

**Comment by itdotnet** [comment]
sorry, I did not understand exactly
please Is is possible explain more precisely?!
Or you give an example?!
Because I am a little amateur

**Comment by Nestad** [comment]
Hi together,

I'm still getting this problem and i reed now all comments i can find but nothing help. 

I want to include the angular-filemanager in a VS2013 Project with already existing aspx-Pages. I already installed Phlanger 4.0 too be able to use php. I add a new aspx file without master page and add the code. 

Steps what i have done:
1. Install like meantioned in documents
2. Changed index.php of localBridge to $fileManagerApi = new FileManagerApi('C:\FTP_dir', 'en');
3. Changed the config like @sachendrapal and @durasj mentioned in there previous commends 'bridges/php/handler.php' to 'bridges/php-local/' for all.

The error i get is 'Error 405 - Bridge response error, please check the API docs or this ajax response.'

Hope you guys can help me to solve this issue.

Thanks and regards

**Comment by jesuscmd** [comment]
Hi, I worked with an important detail, there is two places where you must set the FTP credentials:

1. handler.php line 148
2. includes/Ftp.php line 14

This make everything works fine!!!
