### ISSUE TITLE
Documentation for installing angular-filemanager with PHP Server option

### ISSUE THREAD

**Issue by jrondorf** [joni2back/angular-filemanager#155]
Hi, is there any documentation available how to install angular-filemanager with the PHP Server option, or which PHP version is supported?
When installing on a PHP server, all I get is

- Either *Bridge response error, please check the docs*
- or *bridges/php/handler.php 500 (Internal Server Error)* after installing PHP Classic source files

Thanks!

**Comment by durasj** [comment]
Hello,

by default bridge from @joni2back is used which expects you to use FTP server.

If you want to run it with files hosted next to your code, you can use my [php-local bridge](https://github.com/joni2back/angular-filemanager/tree/master/bridges/php-local).

You can set path that will be used for files in [index.php](https://github.com/joni2back/angular-filemanager/blob/master/bridges/php-local/index.php).

To use my bridge just point all actions in config in index.html to directory with my bridge.

**Comment by joni2back** [comment]
Hi @jrondorf I just updated the Angular-Filemanager in order to show more details about backend errors.
Also I removed the submodule php-classic in order to prevent some kind of errors when users clone the repo.
We dont have some kind of backend bridges yet, but I will take into account for the next changes.

**Comment by jrondorf** [comment]
@durasj Great, works fine. Regarding
```
//Takes two arguments - base path without last slash (default: '$currentDirectory/../files'); language (default: 'en'); mute_errors (default: true, will call ini_set('display_errors', 0))
$fileManagerApi = new FileManagerApi();
```
Modifying the base path does not seem to work. Is there a way to start up the folder tree, e.g. where index.html is stored?

**Comment by jrondorf** [comment]
@durasj Forget my last comment. Everything works as expected. Example:
`$fileManagerApi = new FileManagerApi($_SERVER['DOCUMENT_ROOT'], 'fr');`

**Comment by durasj** [comment]
Glad you got it working.

**Comment by itdotnet** [comment]
hi
I also have a problem. I have the following error
Error 405 - Bridge response error, please check the API docs or this ajax response

In your opinion, what's the problem?!

**Comment by unbreakabl3** [comment]
Hello everyone.
Can you help me please?
ifI just want to use a for example "/tmp/myfiles" folder as my local folder to store files, what exactly i need to change in "index.html" to start use this folder instead default FTP?

Thank you very much!!

**Comment by shreyas-embedded** [comment]
I downloaded the code and tried viewing index.html but it gave me error 1:bridge response error,please check the API docs or this ajax response.
![error1](https://cloud.githubusercontent.com/assets/16622350/23155194/9ece81da-f837-11e6-8267-23680547d465.png)

**Comment by durasj** [comment]
Hi @shreyas-embedded,

try my bundle following the [Usage Instructions](https://github.com/durasj/angular-filemanager/tree/bundle-php-local#usage).

**Comment by mensur** [comment]
@durasj I have tried to install your bundle and I'm getting an error. 
"Function not available". 

![image](https://cloud.githubusercontent.com/assets/80660/23336305/7d28d4c0-fc17-11e6-9cc7-4edaba9165a3.png)

What function is missing?

**Comment by durasj** [comment]
I don't know of any function that could be missing right after the installation.

Can you please tell me what's your setup (web server etc.)?

**Comment by akhilkumar332** [comment]
Error 500 - Bridge response error
![capture1](https://user-images.githubusercontent.com/25744542/37752219-02f422ee-2dbd-11e8-94fb-0d3495209c02.PNG)

![capture2](https://user-images.githubusercontent.com/25744542/37752224-0d441b82-2dbd-11e8-85a4-759932c0cbf7.PNG)

Locally it works fine on xampp, but when i uploaded it online it gives that error.

**Comment by durasj** [comment]
Hi @akhilkumar332, can you check out the AJAX response in the Developer tools or error log on your server?

**Comment by akhilkumar332** [comment]
strange i get this: `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by durasj** [comment]
@akhilkumar332 you need to show me the response of that request - clicking on the address will open Network tab and highlight the request you need to click on. If there will be just some generic error 500, I need the PHP error log from your server. So far the 500 (Internal Server Error) is so broad I can't help you.

**Comment by Produits** [comment]
Hi,

I've got also an error 500.
In the error_log, I've got the following message :
`[error] [client XXXXXX] PHP Parse error:  syntax error, unexpected '[', expecting ')' in /appli/sites/filemanager/bridges/php-local/index.php on line 23, referer: http://XXXXX/filemanager/`

**Comment by durasj** [comment]
Hi @Produits, you are probably running an old version of PHP, try to upgrade to the latest version.

**Comment by Produits** [comment]
Thank you for your answer
I'm running PHP Version 5.3.3 but it works well with PHP Version 5.5.12 on another server... 
Do you know the minimum version of php wich is mandatory ?

**Comment by durasj** [comment]
Technically for the issue you had, >= 5.4 should work. But I would strongly recommend at least PHP 5.6 since it's still receiving security updates (but only for few more months) or PHP 7.x. The newer the better for security and performance.
