### ISSUE TITLE
How to pull data from localhost or my computer

### ISSUE THREAD

**Issue by mayank23er** [joni2back/angular-filemanager#156]
What if i dont want to use FTP and want to pull data from localhost

**Comment by durasj** [comment]
Hello,

by default bridge from @joni2back is used which expects you to use FTP server.

If you want to run it with files hosted next to your code, you can use my [php-local bridge](https://github.com/joni2back/angular-filemanager/tree/master/bridges/php-local) or code your own bridge according to API documentation.

If you will decide to use my bridge, you can set path that will be used for files in [index.php](https://github.com/joni2back/angular-filemanager/blob/master/bridges/php-local/index.php) and just point all actions in config in index.html to directory with my bridge.

**Comment by mayank23er** [comment]
add below line in index.php but still get error 

$fileManagerApi = new FileManagerApi('http://localhost/file-repo');

Do i need to include some files for same?

**Comment by durasj** [comment]
Path should be relative or absolute on your **file system**. So something like 

`$fileManagerApi = new FileManagerApi('../../files');`

And you need to modify your index.html with the config to my bridge. I am enclosing zipped index.html so you get the idea (lines 57-70):
[index.zip](https://github.com/joni2back/angular-filemanager/files/317946/index.zip)

**Comment by mayank23er** [comment]
Awesome any idea how to show total count of files in a folder?

**Comment by durasj** [comment]
Not sure, is it implemented @joni2back? I guess you have to write it yourself.

**Comment by joni2back** [comment]
Not yet, I will take into account for nexts releases... (some kind of status bar)
