### ISSUE TITLE
Get started

### ISSUE THREAD

**Issue by ptitbibice** [joni2back/angular-filemanager#16]
Hi,
can we have a get started or a tutorial for implement your filemanager in wepapplication ?
I have try, pull the project, but i have one error : 

 Strict standards: Declaration of FileManager::download() should be compatible with PHPClassic\Ftp::download($remotePath, $localPath, $mode = 'auto') in /home/dev/htdocs/web4/public/elisracing/angular-filemanager/bridges/php/handler.php on line 101

Thanks

**Comment by joni2back** [comment]
Hi @ptitbibice, I just fixed this bug. Please check now.

Regards!

**Comment by ptitbibice** [comment]
hi,
ty fir your support.
now, i have a internal server error 500 when i create folder.

**Comment by joni2back** [comment]
Have you set the ftp credentials in **handler.php**?
```php
$oFtp = new FileManager(array(
    'hostname' => '',
    'username' => '',
    'password' => ''
));
```

This problem could be related to permissions
```php
$result = $oFtp->mkdir($path .'/'. $name);
if (! $result) {
    throw new Exception("Unknown error creating this folder");
}
```
can you create the folder using ftp software like filezilla?

**Comment by ptitbibice** [comment]
I include your project in my application, so i don't need set the ftp credentials. isn't it ? 
ty @joni2back

**Comment by joni2back** [comment]
If you are including the project in your app, you must use your own backend handler.
This repo handler.php is only for the online demo page...

**Comment by ptitbibice** [comment]
ok

thanks for your support.
Have you already write own backend handler like this?
if you don't have, i go to write this handler for my backend.

Good job for this managerfile

**Comment by joni2back** [comment]
Thank you! Don't forget to give a star to the project :smiley_cat:  :star:
