### ISSUE TITLE
Compress Action in local PHP bridge throws Class 'AngularFilemanager\LocalBridge\ZipArchive' not found error

### ISSUE THREAD

**Issue by jrondorf** [joni2back/angular-filemanager#161]
Trying to compress 2 files will result in following error

`Uncaught Error: Class 'AngularFilemanager\LocalBridge\ZipArchive' not found in <server_path_to_bridge>/LocalBridge/FileManagerApi.php:374`

Even when ZIP PHP extension is installed on the server, and 
`new ZipArchive()`
works in another PHP file on the same server.

Any idea?

**Comment by durasj** [comment]
Hi,

that's most definitely a bug https://github.com/joni2back/angular-filemanager/blob/master/bridges/php-local/LocalBridge/FileManagerApi.php#L373 ... There should be \ in front of the class name. It is a problem with the namespace.

I will fix that soon, thanks for reporting!

**Comment by durasj** [comment]
Hey, @jrondorf could you please try if these changes https://github.com/joni2back/angular-filemanager/compare/master...durasj:patch-2 fixed the problem for you?

**Comment by jrondorf** [comment]
@durasj Perfect, works now! Thanks!

**Comment by joni2back** [comment]
Hi @durasj could you send that MR for this one?
I recomend to declare classes after namespace declaration like..

```php
<?php
namespace Dragon\Ball;
use Exception;
use ZipArchive;

Class Goku {}
