### ISSUE TITLE
Issue in open/closed folder icon of tree

### ISSUE THREAD

**Issue by ishakya** [joni2back/angular-filemanager#162]
If I create two folders named 'a' and 'ajdfasf' respectively. Then, when i click 'ajdfasf' folder, the icon of 'a' folder also changes to open.
![screenshot from 2016-06-21 17-32-42](https://cloud.githubusercontent.com/assets/5999467/16228381/66e31870-37d6-11e6-86a4-2edb247f5d4b.png)

**Comment by joni2back** [comment]
Thanks @ishakya , is fixed now!
