### ISSUE TITLE
The files physically uploaded but not showing it give me "No files in this folder"  

### ISSUE THREAD

**Issue by waleeddbnet** [joni2back/angular-filemanager#164]
I am running the site using IIS 7 on windows server the files already uploaded and i can create the folder but it not show up.

![angularfm](https://cloud.githubusercontent.com/assets/12536669/16410951/7c5ea262-3d2d-11e6-8d59-13f61f850e23.png)

**Comment by joni2back** [comment]
Hi @waleeddbnet which bridge are you using?

**Comment by waleeddbnet** [comment]
PHP > handler.php

**Comment by joni2back** [comment]
Hi... If you are running a FTP on Window server, try to disable the passive mode...
You will need to modify the handler.php file with:
```php
$oFtp = new FileManager(array(
    'hostname' => 'demo',
    'username' => 'demo',
    'password' => 'demo',
    'passive' => false' //<-change this
));

**Comment by tioammar** [comment]
still won't work on Mac ProFTPD
