### ISSUE TITLE
How to use the pickCallback of the filemanager within an angular app?

### ISSUE THREAD

**Issue by Grilly** [joni2back/angular-filemanager#167]
Hi,

I included the filemanager in my app. The file browsing functions work like expected but I can't get my head around the pickCallback.
Is there any further documentation how to use the pickCallback? Well in the example you opened a window.alert and accessed the item properties but how can I trigger showing a modal dialog of ngDialog with my own scope?
Through the pickCallback I want to open a modal dialog where I can select additional options and then send an ajax request to the backend with my options and the item name.

Another question: Is there an option to add multiple custom actions to the contextmenu like multiple pickCallbacks?

Kind regards,
Michael

**Comment by durasj** [comment]
Hi,

pickCallback was meant to be used little bit differently in the situations when you are running angular-filemanager alone and using it ie. as file manager for TinyMCE. That way you can call JS function (global attached at window or anonymous) taking care of filling the file field etc.

I think that in your situation attribute with callback would be more appropriate (which is not implemented atm). Something like:

`<filemanager fm-on-pick="yourMethodFromScope()">`

Just as you would use ng-click.

I think @joni2back can say something more about it and also answer your second question.

Thanks

**Comment by joni2back** [comment]
Hi @Grilly when you use pickCallback, in your particular situation, you can create an event to catch it in your own app...

For example
```js
<script type="text/javascript">
angular.module('FileManagerApp').config(['fileManagerConfigProvider', function (config) {
  config.set({
    pickCallback: function(item) {
        var evt = window.document.createEvent("CustomEvent");
        evt.initCustomEvent("onPickItem", true, true, item);
        window.dispatchEvent(evt);
    }
  });
}]);
</script>

In your app..
```js
window.addEventListener("onPickItem", function(evt) {
    alert(evt.detail);
}, false);

**Comment by joni2back** [comment]
Hi @Grilly we are interested if our workaround to solve your doubt works..
Or if you find another way to do that, could you give more details?

Regards

**Comment by morteza-gho** [comment]
for example I want to select file in file amnager and close [uib modal](http://angular-ui.github.io/bootstrap/#!#modal). I wote this:

**fileManagermodalCtrl** (In main app)

        window.selectFile = function (items) {
            $log.log(items);
            $uibModalInstance.dismiss(items); // selected files `fullPath` will be return -> `/products/img1.jpg`
         };

**index.html** (In file manager index file)

        pickCallback: function (item) {

               var selectedArray = [];

               if( Array.isArray(item) ) { // multiple selection

                  parent.selectFile(item);

               } else { // single multiple selection

                  selectedArray.push(item.fullPath()); 
                  window.parent.selectFile(selectedArray);

               }

        }
