### ISSUE TITLE
POST err500 with angularjs

### ISSUE THREAD

**Issue by wiiliam** [joni2back/angular-filemanager#170]
I've updated FTP credentials in handler.php (except for the hostname field), made the configuration point to php-local in index.html, and for some reason, the only thing I have is read access to files and nothing else.

![rename-error](https://cloud.githubusercontent.com/assets/8944799/17033284/488289d8-4f32-11e6-87ac-3445e6e39232.png)

![2016-07-21-174845_1366x768_scrot](https://cloud.githubusercontent.com/assets/8944799/17043429/66c2192a-4f6b-11e6-9316-2d97289a5333.png)

**Comment by joni2back** [comment]
Hi @wiiliam seems you are using php-local connector instead php connector (that is for ftp use)

**Comment by wiiliam** [comment]
Ahh. Thank you for pointing that out.

**Comment by wiiliam** [comment]
@joni2back Although renaming, deleting and such works now, I'm unable to change the permissions and for some reason, the menu from the three dots turned into a blank bar as shown below:
![2016-07-22-110408_189x63_scrot](https://cloud.githubusercontent.com/assets/8944799/17066471/0c127d12-4ffc-11e6-99cf-601d94931fc3.png)

**Comment by joni2back** [comment]
Seems so weird... Could you create a PR with your changes to check it ?
