### ISSUE TITLE
click on create folder redirect to homepage url

### ISSUE THREAD

**Issue by dmphub01** [joni2back/angular-filemanager#177]
I faced the issue click on create a folder open model pop up and page url are redirect to home url  like

http://localhost/dashboard/#/app/pages/datafiles   file manger page  in click on create folder url changed to home page url  http://localhost/dashboard/#  

 please help..
suribabu

**Comment by mrwogu** [comment]
Hello,
it has been fixed in https://github.com/joni2back/angular-filemanager/commit/d2eaa489073b037afc946cdc4fd0f6c0ca4cfe37

**Comment by joni2back** [comment]
Yes, thanks @mrwogu 
@dmphub01 This is fixed in master branch, you will need to refresh the repo or wait for the next release

**Comment by dmphub01** [comment]
Hi mrwogu

Thanks, now working fine.
