### ISSUE TITLE
icons/table view never changes after a navigating error happens

### ISSUE THREAD

**Issue by liul** [joni2back/angular-filemanager#178]
Hi.

When a navigating error happens (e.g. the backend bridge responses a 500 error when requested listing some dir), the FileNavigator.error is set to some string ( by default, "Unknown error listing, check the response" ). However, the FileNavigator.error is never set back to empty string ("") even when a status 200 action happens afterwards, thus causing the icons/table view sticks with the message "Unknown error listing, check the response". I think a quick fix would be adding these lines of code to FileNavigator.prototype.deferredHandler function at filenavigator.js line 24:

```
if (code == 200) {
    this.error = '';
}
```

**Comment by joni2back** [comment]
Hi.. this is fixed now. Thanks!
