### ISSUE TITLE
folders are not showing properly and loader is showing

### ISSUE THREAD

**Issue by dmphub01** [joni2back/angular-filemanager#179]
Hi ,

File manager is working good  when integrating separately. When i include in my project , folders are not showing properly and loader showing along with folders and tree view  and navigation are showing side by side . Search bar also showing without selecting , Finally showing hide elements. 

I tried other scripts are commented and app.js in some functionality commented , please help 

![issue](https://cloud.githubusercontent.com/assets/19147031/17268601/5f3986e2-564c-11e6-9ed0-b1de5aa6362c.png)

 
Thanks in Advance 
Suribabu

**Comment by NetbearSoftware** [comment]
It looks like a clash with other CSS styles in your project.

I had big issues including angular-filemanager in my project as it overwrites some bootstrap files, and can be overwritten by other CSS libraries depending on the order of inclusion.

I wrote up a ticket #183 to see if this could be improved.

Perhaps you could post a link to your project so we can debug?

Tim

**Comment by dmphub01** [comment]
Hi Netbear

Thank You Very much , Solved the Issue .

Thanks
Suribabu
