### ISSUE TITLE
How to upload files from google drive , drop box  and box 

### ISSUE THREAD

**Issue by dmphub01** [joni2back/angular-filemanager#184]
Hi,

The angular file manager is working Good, you are provided amazing library that features are Good,
I have tried to integrate upload files from google drive, drop box and box but that is not working , Please let me know how to integrate upload file from the tools .Thanks in Advance 

Thanks
Suribabu

**Comment by joni2back** [comment]
Hi @dmphub01, the idea of this project is to provide the front-end interface so, if you want it to use with a custom service, you will need to create your own backend bridge following this **[API documentation] (https://github.com/joni2back/angular-filemanager/blob/master/API.md)**.
