### ISSUE TITLE
This action is not available in the demo

### ISSUE THREAD

**Issue by samkho10** [joni2back/angular-filemanager#187]
Hi,

I have been trying to use the PHP FTP bridge for the past couple of weeks but I keep running into the following error on my browser:

{"result":{"success":false,"error":"This action is not available in the demo","errorDetail":{"type":"Exception","code":0}}

You can find a link to my GitHub project [here](https://github.com/samkho10/angular-filemanager). Any help would be much appreciated 😄

**Comment by joni2back** [comment]
Hi @samkho10 this is because GET requests are not parsing from controllers..
