### ISSUE TITLE
upload files from drop box 

### ISSUE THREAD

**Issue by insideseed** [joni2back/angular-filemanager#189]
Hello,

The file manger functionality is awesome, I tried to integrate Dropbox API ,  But i integrated separately Dropbox API is working fine .
I tried the dist/angular-filemanager.min  file integrate the this drop-box api please help how to integrate the Dropbox api in angular file manager .  

Below Api Code: 
app.js

app.config(['DropBoxSettingsProvider', function(DropBoxSettingsProvider) {

      // Configure the options
        DropBoxSettingsProvider.configure({
            linkType: 'preview',//dropbox link type
            multiselect: false,//dropbox multiselect
            extensions: ['.xls', '.xlsx'],//dropbox file extensions
            box_clientId: '5gv6e9ncnxh7l9c1034prper5x',// box CLient Id
            box_linkType: 'shared',//box link type
            box_multiselect: 'false'//box multiselect
          });
    }])

    .controller('DropBoxCtrl', ['$scope', 'DropBoxSettings', function($scope, DropBoxSettings) {
        $scope.dpfiles = [];
		$scope.url=""
		$scope.valuess=false;
        $scope.remove = function(idx){
            $scope.dpfiles.splice(idx,1);
            }
        $scope.boxfiles = [];
        $scope.removeboxfiles = function(idx){
            $scope.boxfiles.splice(idx,1);
            }
			
    }]);
index.html
<button type="button" id="box-select" class="btn search-button center-block" data-link-type="shared" data-multiselect="false" data-client-id="5gv6e9ncn1032d6gr34prper5x" style="margin-top: 15px;
    margin-bottom: 34px;">Choose a File</button>

<script type="text/javascript" src="https://www.dropbox.com/static/api/2/dropins.js" id="dropboxjs" data-app-key="jrcljhjjmgj"></script>
 <script src="assets/js/dropbox-picker.min.js"></script>

**Comment by joni2back** [comment]
Hi @insideseed to connect angular-filemanager with dropbox I recommend you to create your own bridge using the Dropbox API. Not by javascript.
