### ISSUE TITLE
Running the App

### ISSUE THREAD

**Issue by TTheTesterT** [joni2back/angular-filemanager#19]
I am new at running Angular apps and want to know: how do you get this Angular Filemanager app to work like it is in your demo?

I've tried downloading the app and running "npm init/npm start" and it didn't work.  I've also tried just opening the index.html file and it didn't work.  What steps did you take to run this app?

Also, is it possible for this app to run as a subsection of a different Angular app?

Thanks!

**Comment by joni2back** [comment]
You need to handle a backend server.
In the demo there are a handler written in php.
So... you should clone the repo framework
```bash
jonas@:~/www$ git clone https://github.com/joni2back/angular-filemanager.git --recursive
jonas@:~/www$ cd angular-filemanager/
jonas@:~/www/angular-filemanager$ sudo php -S localhost:80 bridges/php/handler.php
```
Then edit the urls in **[angular-filemanager/assets/js/config.js](https://github.com/joni2back/angular-filemanager/blob/master/assets/js/config.js)**

And compile js ``jonas@:~/www/angular-filemanager$ bash build.sh``

**Comment by TTheTesterT** [comment]
After following your instructions, I've successfully have the HTML/JS/CSS of the site running, but I ran into issues getting various functionalities to work due to errors such as "status 500".

I ran handler.php on localhost:1234, modified the File Manager's config.js to link to http://localhost:1234/, ran build.sh, and use localhost:8100 for the HTML/JS/CSS app itself.  After doing so, I run into the "Access-Control-Allow-Origin" missing header error as shown here ![Missing Access-Control-Allow-Origin Header](https://cloud.githubusercontent.com/assets/12702719/7945802/e931f79e-0927-11e5-8132-b33f3fd00a6b.png)

Along with that, even after adding this line to the top of handler.php right below the <?php:

<pre>header('Access-Control-Allow-Origin: *');</pre>

it still yields the 500 status error (also shown in the above image at the bottom of the web console).

Do you know what I'm missing that prevents the File Manager's server-based functionality from working?

**Comment by joni2back** [comment]
This problem is related to the different ports (front/backend)

Try mounting php built-in server from the root directory...
Example:
```bash
jonas@:~/www$ git clone https://github.com/joni2back/angular-filemanager.git --recursive
jonas@:~/www$ cd angular-filemanager/
jonas@:~/www/angular-filemanager$ sudo php -S localhost:80
```

**Comment by joni2back** [comment]
Can you solve the problem with this?
