### ISSUE TITLE
SFTP Details are not working in PHP Bridge 

### ISSUE THREAD

**Issue by dmphub01** [joni2back/angular-filemanager#195]
Hello ,

I used Amazon  server , I have SFTP details only with Host name, Username and Password But the SFTP details are not working in PHP  Bridge .
I am getting Error "Cannot connect to the FTP server", Please Help how can use SFTP details .

Thanks
Suribabu

**Comment by joni2back** [comment]
Hi @dmphub01 you will need to modify the bridge or create your own sftp brige.
Maybe this can help you http://php.net/manual/es/function.ssh2-sftp.php
