### ISSUE TITLE
Download by button

### ISSUE THREAD

**Issue by ipppinto** [joni2back/angular-filemanager#212]
Hi,

Thank you for you work. Is great!

It's possible to list the files in list by default?
In list mode, It is possible to put a button in front of each file to download?

Thank you

**Comment by joni2back** [comment]
Hi

to change the default view you will need to change main.js controller with this

```js
$scope.viewTemplate = $storage.getItem('viewTemplate') || 'main-icons.html';
```
to this
```js
$scope.viewTemplate = $storage.getItem('viewTemplate') || 'main-table.html';
```

For the second question.. this kind of buttons was in the old template.. was changed for user experience improvement. If you really want to do it, you will need to change in the template file
