### ISSUE TITLE
Zip file is invalide

### ISSUE THREAD

**Issue by ipppinto** [joni2back/angular-filemanager#213]
Hi,

When I download a file as zip in windows I can't open (the error is the folder is invalid).

Thank you

**Comment by ipppinto** [comment]
It's happen to me in http://angular-filemanager.zendelsolutions.com/ too.

**Comment by joni2back** [comment]
Hi... this feature is not implemented in the demo bridge... You will need to write your own.
Remember that the php connector is only to run the demo..
