### ISSUE TITLE
Extract zip error

### ISSUE THREAD

**Issue by ipppinto** [joni2back/angular-filemanager#214]
Hi,

I have this error when I extract a zip. Anyone have this error?

![snap 2016-11-06 at 11 59 02](https://cloud.githubusercontent.com/assets/6302542/20037514/7add6804-a418-11e6-8666-484c9a820757.jpg)

**Headers from console:**

Request URL:http://admin.pt/filemanager/bridges/php/handler.php
Request Method:POST
Status Code:500 Internal Server Error
Response Headers
view source
Connection:keep-alive
Content-Type:text/html
Date:Sun, 06 Nov 2016 11:57:03 GMT
Host-Header:192fc2e7e50945beb8231a492d6a8024
Server:nginx
Transfer-Encoding:chunked
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:pt-PT,pt;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:102
Content-Type:application/json;charset=UTF-8
Cookie:_csrf=af16f5b76b12bf98793be9960c30ae194b2a525d632044a76d0427cdcc67baaea%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22LIYNJaAypWmNau5yfWFk0SFsAPN4wpow%22%3B%7D; PHPSESSID=fr3q37li4nh4rb9e64uflqo8v2
DNT:1
Host:admin.pt
Origin:http://admin.pt
Referer:http://admin.pt/user/gestao-documental-iframe
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36
X-Requested-With:XMLHttpRequest
Request Payload
view source
{action: "extract", item: "/ficheiros/Downloads.zip", destination: "/ficheiros", folderName: "Downl"}
action
:
"extract"
destination
:
"/ficheiros"
folderName
:
"Downl"
item
:
"/ficheiros/Downloads.zip"
Name
common.js	
app.js	
dash_feedback.svg	
KievitWebPro-Light.woff	
handler.php	
Hgo13k-tfSpn0qi1SFdUfVtXRa8TVwTICgirnJhmVJw.woff2	
handler.php

**Preview console:**

{result: {success: false, error: "This action is not available in the demo",…}}
result
:
{success: false, error: "This action is not available in the demo",…}
error
:
"This action is not available in the demo"
errorDetail
:
{type: "Exception", code: 0}
code
:
0
type
:
"Exception"
success
:
false

**Comment by joni2back** [comment]
Hi... this feature is not implemented in the demo bridge... You will need to write your own.
Remember that the php connector is only to run the demo..
