### ISSUE TITLE
Where is the python bridge? 

### ISSUE THREAD

**Issue by happystory** [joni2back/angular-filemanager#218]
Thanks a lot!

**Comment by gordol** [comment]
I've been very tempted to put one together that uses Mongo's GridFS with a Python middleware, but will need to build directory and permissions abstractions. It seems to me though that this thing is sorta more geared towards something like an FTP server, exposed over the web.

**Comment by xiongyihui** [comment]
just write one, see https://github.com/joni2back/angular-filemanager/pull/222
