### ISSUE TITLE
Error: Invalid input data

### ISSUE THREAD

**Issue by milesholt** [joni2back/angular-filemanager#22]
Hi,

Getting this error now, when loading the page, the status just remains at 'loading...' ?

Thanks

**Comment by joni2back** [comment]
Can you reproduce the error?
What backend handler are u using?

**Comment by milesholt** [comment]
Using the php handler. 

When hitting refresh or loading the page, the error is reproduced.

[Error] Error: Invalid input data
Chmod@http://.../js/angular-filemanager/assets/js/chmod.js:16:36
Item@http://.../js/angular-filemanager/assets/js/item.js:12:33
http://.../js/angular-filemanager/assets/js/filenavigator.js:32:48
s@http://.../js/angular-filemanager/assets/ext/angular.min.js:7:306
http://.../js/angular-filemanager/assets/js/filenavigator.js:31:32
http://.../js/angular-filemanager/assets/ext/angular.min.js:81:200
http://.../js/angular-filemanager/assets/ext/angular.min.js:112:344
$eval@http://.../js/angular-filemanager/assets/ext/angular.min.js:126:193
$digest@http://.../js/angular-filemanager/assets/ext/angular.min.js:123:291
$apply@http://.../js/angular-filemanager/assets/ext/angular.min.js:126:478
l@http://.../js/angular-filemanager/assets/ext/angular.min.js:81:495
O@http://.../js/angular-filemanager/assets/ext/angular.min.js:86:114
onload@http://.../js/angular-filemanager/assets/ext/angular.min.js:87:125
	(anonymous function) (angular.min.js, line 103)
	(anonymous function) (angular.min.js, line 77)
	(anonymous function) (angular.min.js, line 112)
	$eval (angular.min.js, line 126)
	$digest (angular.min.js, line 123)
	$apply (angular.min.js, line 126)
	l (angular.min.js, line 81)
	O (angular.min.js, line 86)
	onload (angular.min.js, line 87)

Thanks

**Comment by joni2back** [comment]
Can you please paste the API List json response?
The issue might be the value of the property ```rights```

**item.js**
```js
perms: new Chmod(model && model.rights),
```

**chmod.js**
```js
var codes = isNaN(initValue) ?
    this.convertfromCode(initValue):
    this.convertfromOctal(initValue);
if (! codes) {
    throw new Error('Invalid input data');
}
```

**Comment by milesholt** [comment]
This is the response. Looking at the log, it seems to list the contents okay, it's just not showing them?

Thanks

![screen shot 2015-06-05 at 10 07 23](https://cloud.githubusercontent.com/assets/2687598/8002875/27c63418-0b6a-11e5-9db0-23efb2e74827.png)

**Comment by joni2back** [comment]
Please, in your chmod.js file, can you replace this:

```js
if (! codes) {
    throw new Error('Invalid input data');
}
```

For this:
```js
if (! codes) {
    throw { data_that_generate_error: initValue }
}
```

Then.. rebuild the assets (if you have troubles doing this, tell me and i suggest other option to do it)
```bash
jonas@:~/angular-filemanager$ bash build.sh --prevent-minify
```

And paste here the browser console error (in order to display the value that broken the chmod instance)
Thanks!!

**Comment by joni2back** [comment]
@milesholt ?

**Comment by milesholt** [comment]
Hi, sorry I've been away.

I think this is right?

![screen shot 2015-06-12 at 13 11 20](https://cloud.githubusercontent.com/assets/2687598/8129748/2055589a-1104-11e5-9049-12d6158042c4.png)


Thanks

**Comment by milesholt** [comment]
![screen shot 2015-06-12 at 13 13 45](https://cloud.githubusercontent.com/assets/2687598/8129766/54055c3a-1104-11e5-802a-5d1218744840.png)

**Comment by joni2back** [comment]
Exactly... 
Are you working with a ftp handler? (backend connector)

```total``` is not valid parameter to create a chmod instance.. 
You could do the following:
 * Replace this with an empty (or correct) value from the server side 
 * Change the exception with a fake value.. for example (chmod.js)
```js
if (! codes) {
    codes = {
        owner:{read:true,write:true,exec:true},
        group:{read:true,write:true,exec:true},
        others:{read:true,write:true,exec:true}
    };
}
```

**Comment by milesholt** [comment]
That's great, I can now see it thanks.. But, and I hate to say it,  other problems seem to be arising? I can't seem to rename folders and the it seems to be duplicating within itself when selecting a folder?

![screen shot 2015-06-12 at 14 36 05](https://cloud.githubusercontent.com/assets/2687598/8131733/3c733eec-1114-11e5-8a7d-0d369a4394e5.png)

**Comment by joni2back** [comment]
This behavior is so weird.
Do you have a link to test? or paste the JSON response of your handler.

**Comment by milesholt** [comment]
Hi,

Actually that was caused by an error on my part, all fixed. Regarding the renaming issue, I can see there is no function yet, so that's fine, I can sort that.

Thanks again for your help!
