### ISSUE TITLE
Error opening TXT-Files with ISO-8859-2

### ISSUE THREAD

**Issue by logtron** [joni2back/angular-filemanager#223]
Hello Angular-Filemanager Team,

having Problems with showing Files with encoding ISO-8859-2 that contains (äöüÄÖÜß)
After change encoding (iconv -f ISO-8859-2 -t UTF-8 Input.txt -o Output.txt)
we can open Output.txt in Filemanager.

Thanks
![2016-12-01 15_21_27](https://cloud.githubusercontent.com/assets/19145058/20797190/034a743c-b7da-11e6-8ed2-093d37de825b.png)

**Comment by logtron** [comment]
Dirty little hack for bridges/php/handler.php to handle non UTF-8 Files 
(all non UTF-8 Files are handled as ISO-8859-2 Files).

```
class FileManager extends Ftp
{
    public function downloadTemp($path)
    {
        $localPath = tempnam(sys_get_temp_dir(), 'fmanager_');
        if ($this->download($path, $localPath)) {
            return $localPath;
        }
    }
    public function getContent($path)
    {
        $localPath = $this->downloadTemp($path);
        if ($localPath) {
            $localContent = @file_get_contents($localPath);
            if (mb_detect_encoding($localContent, "UTF-8", true) != false) {
                return $localContent;
            } else {
                return mb_convert_encoding($localContent, "UTF-8", "ISO-8859-2");
            }
        }
    }
}
```

**Comment by joni2back** [comment]
@logtron thanks for report this.
