### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by GlauberF** [joni2back/angular-filemanager#227]
Hello, I really liked your work, would you have this same project in angular 2 or vue.js?

**Comment by joni2back** [comment]
Hi @GlauberF .
Not yet.

**Comment by GlauberF** [comment]
Could you tell me, how could I login to it using jwt?
Another detail I noticed, it sends 2 requests, one OPTION and another GET, it only takes the result of the first one, which does not return anything.
The second, which is the GET request, is returning the directory all right
