### ISSUE TITLE
Could you add a LICENSE, please?

### ISSUE THREAD

**Issue by silentHoo** [joni2back/angular-filemanager#23]
Your project is very fancy, thanks for the good work. But there is no license available. So could you please add one?

Thank you in advance!

**Comment by joni2back** [comment]
Hi @silentHoo thank you.
MIT is the project license. I just added to the readme file in order to clarify the visibility.

Don't forget to give a star :star: Thanks!

**Comment by silentHoo** [comment]
Thank you, and I already starred your project ;)

**Comment by joni2back** [comment]
@silentHoo Hello, I look your fork and the things you are doing are great.. bower compatibility and cached templates..
When you finish can you send a pull request ?
Regards!

**Comment by silentHoo** [comment]
Yupp, that's the plan ;) I'll mod your project a bit to fit my needs, but I'll try to make it in a simple and clean way, so I'll make a PR when I'm done :)
