### ISSUE TITLE
raspberry pi media server

### ISSUE THREAD

**Issue by mkeyno** [joni2back/angular-filemanager#230]
sorry guys to open ticket for my question , but I'm trying to let my raspberry pi connected client, share media files from storage connected to raspberry pi , I've already install NAS server but its not beautiful as your file manger lib , can you advise me how to use your lib for such media server

**Comment by joni2back** [comment]
Hi.. You will need to install an apache or nginx server on your raspberry (of course with php).

Also you can do it only with php built server (for dev purposes) http://php.net/manual/en/features.commandline.webserver.php
