### ISSUE TITLE
php-local file name encoding

### ISSUE THREAD

**Issue by swer21** [joni2back/angular-filemanager#244]
I'm using php-local and discovered some problems with file name encoding.
For example  "Die Ärzte" was shown as "Die Ãrzte". As a result the folder was not  browseable.

I fixed it by  removing  utf8_encode from bridges/php-local/LocalBridge/FileManagerApi.php.

Is this safe or is there a better way to fix the problem?

**Comment by durasj** [comment]
Hi @swer21,

I will be taking a look at this soon as I also experienced this with some other people.

**Comment by joni2back** [comment]
Hi @durasj this was fixed in your last PR ?

**Comment by durasj** [comment]
Hi @joni2back, yes, that's right.

**Comment by joni2back** [comment]
Hi @swer21 this is now fixed in master
