### ISSUE TITLE
This is demo?

### ISSUE THREAD

**Issue by tufkan** [joni2back/angular-filemanager#252]
This project is demo??? If not, how can I fix it?
<img src="http://image.prntscr.com/image/05cdf196ad7c454cbd57bdc0cebe70ad.png">

**Comment by tufkan** [comment]
Help me please

**Comment by joni2back** [comment]
The source code of the backend connector Yes.. Is a demo to use the angular-filemanager.
You have here all the frontend/javascript part... You will only need to build your own backend connector in any language

**Comment by tufkan** [comment]
From which codes can demo passive?

**Comment by tufkan** [comment]
@joni2back how can build your own backend connector in any language 

What is the File name???
