### ISSUE TITLE
How to include in existing MVC-C#-Angularjs-1.5.8-AngularMaterial-v1.1.1 based Project

### ISSUE THREAD

**Issue by Jeelani786** [joni2back/angular-filemanager#258]
Hi, I am trying to include your project inside my project which is built using **MVC 5(C#)+Angularjs-1.5.8+AngularMaterial -v1.1.1**. How do I include if you have any guidelines for that then please provide. Right now I have included as below and getting this error([$injector:unpr] Unknown provider: fileManagerConfigProvider). and see nothing on the screen.
**And currently I am not using any bridge, simply wants to use a shared network folder because the app is used inside the environment**.
`@*<script src="~/Areas/SalesManagement/Controllers/NGPreSalesAPI/FileManager/angular/angular.min.js"></script>*@
<script src="~/Areas/SalesManagement/Controllers/NGPreSalesAPI/FileManager/angular-translate/angular-translate.min.js"></script>
<script src="~/Areas/SalesManagement/Controllers/NGPreSalesAPI/FileManager/ng-file-upload/ng-file-upload.min.js"></script>
<script src="~/Areas/SalesManagement/Controllers/NGPreSalesAPI/FileManager/jquery/dist/jquery.min.js"></script>
<script src="~/Areas/SalesManagement/Controllers/NGPreSalesAPI/FileManager/bootstrap/dist/js/bootstrap.min.js"></script>
<link href="~/Areas/SalesManagement/Controllers/NGPreSalesAPI/FileManager/bootswatch/paper/bootstrap.min.css" rel="stylesheet" />

<link href="~/Areas/SalesManagement/Controllers/NGPreSalesAPI/FileManager/angular-filemanager.min.css" rel="stylesheet" />
<script src="~/Areas/SalesManagement/Controllers/NGPreSalesAPI/FileManager/angular-filemanager.min.js"></script>

<angular-filemanager></angular-filemanager>

<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-35182652-1', 'auto');
    ga('send', 'pageview');
</script>

<script type="text/javascript">
    //example to override angular-filemanager default config
    angular.module('GAiiNSApp').config(['fileManagerConfigProvider', function (config) {
        var defaults = config.$get();
        config.set({
            appName: 'angular-filemanager',
            pickCallback: function (item) {
                var msg = 'Picked %s "%s" for external use'
                  .replace('%s', item.type)
                  .replace('%s', item.fullPath());
                window.alert(msg);
            },

            allowedActions: angular.extend(defaults.allowedActions, {
                pickFiles: false,
                pickFolders: false,
            }),
        });
    }]);
</script>`
I have excluded yours angularjs.min.js bcoz I already have 1.5.8 version, just let me know the proper guidelines.
Thanks.

**Comment by durasj** [comment]
Hi @Jeelani786, I think you are missing the config. [as can be seen in the README](https://github.com/joni2back/angular-filemanager#extending-the-configuration-file).

Btw you'll need to use some "bridge". Because you can't simply access the FS using the plain web browser. The bridge connects your filesystem with the web interface.

You can write one yourself or use one of the provided bridges.

**Comment by Jeelani786** [comment]
Hi **@durasj**, I have exactly no idea about how to write bridge, can you explain how to do that in ASP.Net MVC 5 C#. 
Thanks.

**Comment by durasj** [comment]
Hi @Jeelani786,

you need to create HTTP server in ASP.Net (not sure how to do it, I've never wrote a single line in it) following the [API docs](https://github.com/joni2back/angular-filemanager/blob/master/API.md).
