### ISSUE TITLE
[php-local-bridge]problem listing files under some folder with '!'

### ISSUE THREAD

**Issue by slime7** [joni2back/angular-filemanager#262]
hi @durasj 
Php-local cant list files under folder with '!'. example '[Kono Subarashii Sekai ni Shukufuku o! 2][s2-01-10 END][720p][GB]' or '[CASO&SumiSora][Sound!Euphonium2][01][GB][720P][01-13]'. `bridges/php-local/index.php` just return `[]`.
![3](https://cloud.githubusercontent.com/assets/8674371/25077844/28da58a6-2360-11e7-9ed4-6e59064e40a9.png)

**Comment by durasj** [comment]
Hi @slime7,

I can easily reproduce the issue. Characters like []!* are causing issues since globbing is used for listing. I changed that in the [current bundle](https://github.com/durasj/angular-filemanager/tree/bundle-php-local) and hopefully it'll also be soon in the main repo.

**Comment by slime7** [comment]
@durasj, It works on every character now, thanks.
