### ISSUE TITLE
Recursive Search functionality does not work.

### ISSUE THREAD

**Issue by damiankaczkowski** [joni2back/angular-filemanager#266]
Hello.

I am currently using @durasj local bundle. When I am trying to search for file it only find files in current directory, it does not search recursively. I have tried to find some option to control this behavior here:

https://github.com/joni2back/angular-filemanager/blob/master/src/js/providers/config.js

But I failed to find one.

Is this a bug or by design? If this is by design, do you plan to implement recursive search?

Greets.

**Comment by durasj** [comment]
Hello @damiankaczkowski,

I don't believe feature like that is currently implemented in the whole project, not only in the php local bridge.

I don't think there are any plans to do so. I believe PRs are always welcome.

**Comment by joni2back** [comment]
Hi @damiankaczkowski the search functionality for the moment is only for the current folder.
