### ISSUE TITLE
Can't Edit Files

### ISSUE THREAD

**Issue by myhexa** [joni2back/angular-filemanager#274]
Hello!

I just installed the File Manager on my website. I am getting this error now when I try editing a file. I also can't delete files.

![screenshot 2017-05-11 at 10 39 55 pm](https://cloud.githubusercontent.com/assets/26014766/25981440/c661ac8a-369a-11e7-8be1-ce80ee84da1f.png)

Thanks!

Hexa
https://hexa.gq

**Comment by joni2back** [comment]
Hi @myhexa . As the message says this action is not available in the demo.
We provide only the frontend for this file manager, but for the backend side you will need to create your own connector.
