### ISSUE TITLE
How to open/close access for certain user

### ISSUE THREAD

**Issue by bzvyagintsev** [joni2back/angular-filemanager#276]
Is it possible to change access setting for certain user in frontend?

I create simple user model in database and have variable in angular {{currentUser}}.
How can I change the permissions for this user? For example hide specific folders, or change basePath?

I try to create folders for every user, and change basePath (in Angular main controller) for them, but if I change basePath like this:

`config.basePath = '/' + user.group +'/' user.username `

I have some bugs:
1. breadcrumbs showing Filemanager / group / username - but I dont want group in breadrumbs, I want username folder as ROOT,
2. Tree view in side bar also show wrong structure.

Are there any other and more simple ways to create user rights (to hide certain folders or create user specific folders).

**Comment by joshribakoff** [comment]
Separate folders per user perhaps? Or modify the backend bridge to omit files. This really isn't any concern for the user interface in my opinion, it's logic that belongs in your backend...

**Comment by joni2back** [comment]
Hello @bzvyagintsev I totally agree with @joshribakoff this needs to be fully covered from backend bridge.

Btw if your app is not using any kind of session, maybe you can pass those vars by url extending the config... example

```html
<script type="text/javascript">
angular.module('FileManagerApp').config(['fileManagerConfigProvider', function (config) {
  var defaults = config.$get();
  config.set({
    listUrl: 'bridges/php/' + currentUser +'/handler.php'
  });
}]);
</script>
