### ISSUE TITLE
Can I Set Root Path?

### ISSUE THREAD

**Issue by HowToDoThis** [joni2back/angular-filemanager#283]
Hi, my webhosting was link ftp with / instead of public_html/ , anyways can change the path to /public_html/"something" ?

#the webhosting I using was [000webhosting](https://www.000webhost.com/)

**Comment by joni2back** [comment]
Hey! Extend the config file as the doc says..

```html
<script type="text/javascript">
angular.module('FileManagerApp').config(['fileManagerConfigProvider', function (config) {
  var defaults = config.$get();
  config.set({
   basePath: '/my/custom/path'
  });
}]);
</script>
```
