### ISSUE TITLE
I know This is DEMO, But How To Write PHP Connector...

### ISSUE THREAD

**Issue by HowToDoThis** [joni2back/angular-filemanager#289]
Sooooooooo, I know THIS was DEMO Version of angular-file manager, and i read a lot issues before, but i want to know, how can us write a PHP Connector Of it?

#i just a newbie, starting codding in 1 months only

**Comment by ericksonnascimento** [comment]
Just check [here](https://github.com/joni2back/angular-filemanager/tree/master/bridges/php)
