### ISSUE TITLE
working with ASP.NET

### ISSUE THREAD

**Issue by MostafaEakram** [joni2back/angular-filemanager#291]
Hi
I am try to implement this in my .net project but i cant . Would you please give me a sample project so that i can understand and use your things

**Comment by joni2back** [comment]
You will need to make your own ASP bridge following the [connector API](https://github.com/joni2back/angular-filemanager/tree/master/API.md). 
Also you can check our example bridges in many languages [here](https://github.com/joni2back/angular-filemanager/tree/master/bridges).
