### ISSUE TITLE
Input type: XML?

### ISSUE THREAD

**Issue by BaigSahaab** [joni2back/angular-filemanager#292]
Hey there,

i just want to know, can we give directory listing in an XML tree form, i mean can we give it XMl file and this will do the structure as it does with the path/directory given?

**Comment by joni2back** [comment]
hey @BaigSahaab you can do it reading the xml from backend side (connectors) and returning a correct json for the front

**Comment by BaigSahaab** [comment]
As i am exporting Android Directory Listing in XML format not the files or path, just need to display directory listing like it does with path or directory and on server end i am using php, so can u particularly let me know, where to connect my XML connector.?
