### ISSUE TITLE
NavBar issues?

### ISSUE THREAD

**Issue by BaigSahaab** [joni2back/angular-filemanager#293]
Hey there, thanks for the support earlier,
i need to know how to change navbar options, like i want to remove some lang and a upload button, 
i manage to find that in src/templates i guess. but when i try to change the lang or any other thing in navbar.html, nothing changes on the front end. Help!!

**Comment by joni2back** [comment]
You will need to compile the assets/views 
(install node, install npm) then run ```npm install``` and then ```gulp build```
