### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by majidbigdeli** [joni2back/angular-filemanager#297]
i am using gulp 
my gulp file is
`          'use strict';

      var
         gulp = require('gulp'),
         child = require('child_process'),
         fs = require('fs'),
    runSequence = require('run-sequence'),
    concat = require('gulp-concat'),
    sass = require('gulp-sass'),
    uglify = require('gulp-uglify'),
    browserSync = require('browser-sync'),
    uglifycss = require('gulp-uglifycss'),
    ngAnnotate = require('gulp-ng-annotate'),
    imagemin = require('gulp-imagemin'),
    size = require('gulp-size'),
    nodemon = require('gulp-nodemon'),
    exec = require('gulp-exec'),
    exec = require('child_process').exec,
    os = require('os'),
    open = require('gulp-open'),
    server = require('gulp-express'),
    supervisor = require("gulp-supervisor"),
    prompt = require('gulp-prompt'),
    readline = require('readline'),
    jsonfile = require('jsonfile'),
    inquirer = require('inquirer'),
    opn = require('opn'),
    mkdirp = require('mkdirp').sync,
    pathExists = require('path-exists');
         //minify
            gulp.task('js', function () {
           return gulp.src([
           //liberry
          './bower_components/jquery/dist/jquery.js',
          // './bower_components/semantic/dist/semantic.js',
          './bower_components/bootstrap/dist/js/bootstrap.js',
           './bower_components/angular/angular.min.js',
          './bower_components/angular-ui-router/release/angular-ui-router.js',
           './bower_components/ng-file-upload/ng-file-upload.js',
          './bower_components/ng-file-upload/ng-file-upload-all.js',
          './bower_components/ng-file-upload/ng-file-upload-shim.js',
          './bower_components/moment/moment.js',
          './bower_components/moment-jalaali/build/moment-jalaali.js',
          './bower_components/angular-ui-notification/dist/angular-ui-notification.js',
          './bower_components/angular-jwt/dist/angular-jwt.js',
         './bower_components/angular-sanitize/angular-sanitize.js',
         './bower_components/angular-translate/angular-translate.js',
          './bower_components/angular-translate-handler-log/angular-translate-handler-log.js',
          './bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.js',
          './bower_components/angular-cookies/angular-cookies.js',
         './bower_components/angular-translate-storage-cookie/angular-translate-storage-cookie.js',
          './bower_components/angular-translate-storage-local/angular-translate-storage-local.js',
          './node_modules/ng-table/bundles/ng-table.js',
           './client/directive/dropDown_multiselect.js',

          './node_modules/angular-filemanager-fkoester/dist/angular-filemanager.min.js',

               //app
              './client/app.js',
              //service
               './client/service/**/*.js',

              //directive
               './client/directive/checkgroupUserName.js',
              './client/directive/ckeditorangular.js',
       //  './client/directive/string.js',
          //run
           './client/run/run.js',

        //controoler
          './client/component/**/*.js'

    ])
        .pipe(concat('app.min.js'))
        .pipe(ngAnnotate({
            // true helps add where @ngInject is not used. It infers.
            // Doesn't work with resolve, so we must be explicit there
            add: true
        }))

        .pipe(uglify())
        .pipe(gulp.dest('./client/content/js'))
        });

my app.js file
`         "use strict";
           App = angular.module("app", ["ui.router", "ngTable", "ngCookies", "ngFileUpload", "ui-notification", 
         "angular-jwt", 'pascalprecht.translate', "ngSanitize", "angularjs-dropdown-
          multiselect","FileManagerApp"]);
         App.config(["$urlRouterProvider", "$locationProvider", '$qProvider', "$stateProvider", 
         "NotificationProvider", "$translateProvider","fileManagerConfigProvider", function 
           ($urlRouterProvider, $locationProvider, $qProvider, $stateProvider, NotificationProvider, 
           $translateProvider,config) {
   
    var defaults = config.$get();
    config.set({
      appName: 'angular-filemanager',
      pickCallback: function(item) {
        var msg = 'Picked %s "%s" for external use'
          .replace('%s', item.type)
          .replace('%s', item.fullPath());
        window.alert(msg);
      },
  
      allowedActions: angular.extend(defaults.allowedActions, {
        pickFiles: true,
        pickFolders: false,
      }),
    });
  
   
    $qProvider.errorOnUnhandledRejections(false);
    $translateProvider
        .useStaticFilesLoader({
            prefix: '/translations/',
            suffix: '.json'
        })
        .preferredLanguage('fa')
        .useLocalStorage()
        .useSanitizeValueStrategy('escapeParameters')
        .useMissingTranslationHandlerLog();
    NotificationProvider.setOptions({
        delay: 2000,
        startTop: 20,
        startRight: 10,
        verticalSpacing: 20,
        horizontalSpacing: 20,
        positionX: 'center',
        positionY: 'top'
    });
    $urlRouterProvider.otherwise("/");
    $stateProvider
        .state("login", {
            url: "/",
            templateUrl: './component/login/login.html',
            controller: 'loginCtrl'
        }).state("main", {
            url: "/",
            abstract: true,
            templateUrl: './component/main/main.html',
            controller: 'mainCtrl',
            resolve: { /* @ngInject */
                authenticate: function ($q, userService, $state, $timeout) {
                    userService.isAuthenticated().then(function (resp) {

                        if (resp.data.status) {
                            // Resolve the promise successfully
                            return $q.when()
                        } else {
                            // The next bit of code is asynchronously tricky.

                            $timeout(function () {
                                // This code runs after the authentication promise has been rejected.
                                // Go to the log-in page
                                $state.go('login')
                            })

                            // Reject the authentication promise to prevent the state from loading
                            return $q.reject()
                        }

                    }, function (err) {
                        $state.go('login')

                    })
                }
            }
        }).state("main.profile", {
            url: "profile",
            views: {
                "panel@main": {
                    templateUrl: './component/profile/profile.html',
                    controller: 'profileCtrl',
                }
            }
        }).state("main.registerSingle", {
            url: "registerSingle",
            views: {
                "panel@main": {
                    templateUrl: './component/register/registerSingle.html',
                    controller: 'registerSingleCtrl'
                }
            }
        }).state("main.editProfile", {
            url: "editProfile",
            views: {
                "panel@main": {
                    templateUrl: './component/editProfile/editProfile.html',
                    controller: 'editProfileCtrl'
                }
            }
        }).state("main.registerSeveral", {
            url: "registerSeveral",
            views: {
                "panel@main": {
                    templateUrl: './component/register/registerSeveral.html',
                    controller: 'registerSeveralCtrl'
                }
            }
        }).state("recoveryPassword", {
            url: "/recovery",
            templateUrl: "./component/recoveyPassword/recoverypassword.html",
            controller: "recoveryPasswordCtrl"
        }).state("main.manageUser", {
            url: "userManager",
            views: {
                "panel@main": {
                    templateUrl: "./component/manageUser/manage-user.html",
                    controller: "manageUserCtrl"
                }
            }
        }).state("main.editUser", {
            url: "editUser/{id}",
            views: {
                "panel@main": {
                    templateUrl: "./component/editUser/editUser.html",
                    controller: "editUserCtrl"
                }
            }
        }).state("main.Quece", {
            url: "quece",
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/quence.html",
                    controller: "quenceCtrl"
                }
            }
        }).state("main.agent", {
            url: "agent",
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/agent.html",
                    controller: "agentCtrl"
                }
            }
        }).state("main.uploadSound", {
            url: "uploadSound",
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/uploadSound.html",
                    controller: "uploadSoundCtrl"

                }
            }
        }).state("main.ManageQuence", {
            url: "manageQuece",
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/manageQuece.html",
                    controller: "manageQueceCtrl"
                }
            }
        }).state("main.Tier", {
            url: "Tier",
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/tier.html",
                    controller: "tierCtrl"
                }
            }
        }).state("main.manageUserNumber", {
            url: "manageUserNumber",
            views: {
                "panel@main": {
                    templateUrl: "./component/manageUserNumber/manageUserNumber.html",
                    controller: "manageUserNumberCtrl"
                }
            }

        }).state("main.addUserNumber", {
            url: "addUserNumber/:id",
            params: {
                id: { squash: true, value: null },
            },

            views: {
                "panel@main": {
                    templateUrl: "./component/manageUserNumber/addUserNumber.html",
                    controller: "addUserNumberCtrl"
                }
            }
        }).state("main.editUserNumber", {
            url: "editUserNumber/:id",
            params: {
                id: { squash: true, value: null },
            },
            views: {
                "panel@main": {
                    templateUrl: "./component/manageUserNumber/editUserNumber.html",
                    controller: "editUserNumberCtrl"
                }
            }
        }).state("main.editQuece", {
            url: "editQuece/:id",
            params: {
                id: { squash: true, value: null },
            },
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/editQuece.html",
                    controller: "editQueceCtrl"
                }
            }
        }).state("main.editQueceTier", {
            url: "editQueceTier/:id",
            params: {
                id: { squash: true, value: null },
            },
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/editQueceTier.html",
                    controller: "editQueceTierCtrl"
                }
            }

        }).state("main.ManageAgent", {
            url: "manageAgent",
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/manageAgent.html",
                    controller: "manageAgentCtrl"
                }
            }
        }).state("main.editAgent", {
            url: "editAgent/{id}",
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/editAgent.html",
                    controller: "editAgentCtrl"
                }
            }
        }).state("main.editAgentTier", {
            url: "editAgentTier/{id}",
            views: {
                "panel@main": {
                    templateUrl: "./component/callCenter/editAgentTier.html",
                    controller: "editAgentTierCtrl"
                }
            }
        }).state("main.script", {
            url: "script",
            views: {
                "panel@main": {
                    templateUrl: "./component/scriptPage/scriptPage.html",
                    controller: "AceCtrl"
                }
            }
        }).state("main.manageScript", {
            url: "manageScript",
            views: {
                "panel@main": {
                    templateUrl: "./component/scriptPage/manageScript.html",
                    controller: "manageScriptCtrl"
                }
            }
        }).state("main.editScript", {
            url: "editScript/{id}",
            views: {
                "panel@main": {
                    templateUrl: "./component/scriptPage/editScript.html",
                    controller: "editScriptCtrl"
                }
            }
        }).state("main.createGroupUser", {
            url: "createGroupUser",
            views: {
                "panel@main": {
                    templateUrl: "./component/group/groupUser.html",
                    controller: "createGroupUserCtrl"
                }
            }
        }).state("main.manageGroupUser", {
            url: "manageGroupUser",
            views: {
                "panel@main": {
                    templateUrl: "./component/group/manageGroupUser.html",
                    controller: "manageGroupUserCtrl"
                }
            }
        }).state('main.editGroupUser', {
            url: "editGroupUser/{id}",
            views: {
                "panel@main": {
                    templateUrl: "./component/group/editGroupUser.html",
                    controller: "editGroupUserCtrl"
                }
            }
        }).state("main.RPDI", {
            url: "RPDI",
            views: {
                "panel@main": {
                    templateUrl: "./component/RPDI/RPDI.html",
                    controller: "RpdiCtrl"
                }
            }
        }).state("main.AddRdpi", {
            url: "AddRdpi",
            views: {
                "panel@main": {
                    templateUrl: "./component/RPDI/AddRdpi.html",
                    controller: "AddRdpiCtrl"
                }
            }
        }).state("main.AddManagerProject", {
            url: "AddManagerProject",
            views: {
                "panel@main": {
                    templateUrl: "./component/managerProject/addManagerProject.html",
                    controller: "AddManagerProjectCtrl"
                }
            }
        }).state("main.ManagerProject", {
            url: "ManagerProject",
            views: {
                "panel@main": {
                    templateUrl: "./component/managerProject/managerProject.html",
                    controller: "ManagerProjectCtrl"
                }
            }
        })
        .state("main.AddMessage", {
            url: "AddMessage",
            views: {
                "panel@main": {
                    templateUrl: "./component/Message/addMessage.html",
                    controller: "AddMessageCtrl"
                }
            }
        }).state("main.Tanzimat", {
            url: "Tanzimat",
            views: {
                "panel@main": {
                    templateUrl: "./component/Tanzimat//Tanzimat.html",
                    controller: "TanzimatCtrl"
                }

            }

        })

    $locationProvider.html5Mode(true);

       }]);`

when my add angular-filemanager to project i have two error
1-Uncaught ReferenceError: require is not defined
2-Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.6.5/$injector/modulerr

what????

**Comment by durasj** [comment]
Honestly, this will be hardly an issue in the angular-filemanager. Have you tried writing on som online forum for help?

**Comment by musaurabh** [comment]
Hi @majidbigdeli where you able to find any solution? I'm getting #336  as well.
