### ISSUE TITLE
Upload Not work 8 mb file PPT File

### ISSUE THREAD

**Issue by viralchauhan** [joni2back/angular-filemanager#298]
dear joni2back,
i have one pptx file this file size is 12 mb, this file not upload in ftp.
getting Error message is  **This action is not available in the demo**
 i already increase size PHP.ini file .
how to fix this issues.

**Comment by joni2back** [comment]
Check also your webserver configuration for example the max post size of apache.

**Comment by viralchauhan** [comment]
; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 200M

post_max_size 200M
max_input_time 800
max_execution_time 800


; Maximum number of files that can be uploaded via a single request
max_file_uploads = 30

;;;;;;;;;;;;;;;;;;
; Fopen wrappers ;
;;;;;;;;;;;;;;;;;;

; Whether to allow the treatment of URLs (like http:// or ftp://) as files.
; http://php.net/allow-url-fopen
allow_url_fopen = On

; Whether to allow include/require to open URLs (like http:// or ftp://) as files.
; http://php.net/allow-url-include
allow_url_include = Off


![fileupload issues](https://user-images.githubusercontent.com/6339022/31160247-b410a1d4-a8ec-11e7-9172-858b3e3cc96c.png)

**Comment by joni2back** [comment]
Check my answer in #304 (duplicates with #304)
