### ISSUE TITLE
question about upload multi files with spring mvc 

### ISSUE THREAD

**Issue by mzyfree** [joni2back/angular-filemanager#301]
since this great file manager supports java local file system, and my question is how to get the MultipartFile Http request without change the default ng front code.
Under one file ,it is easy,just like this:
//    public @ResponseBody HttpResponse uploadFile(@RequestParam("file-0") MultipartFile file, 
//    		@RequestParam("destination")String destPath){....}
but under multi files???
it will be file-1,file-2....
anyone help?
Tks.

**Comment by marcoserafini2** [comment]
If you want to use `@RequestParam(name="file") List<MultipartFile> files`, the only solution I found was to do the override in the Upload method.
I created a bridge written in Java with Spring, you find it[ here](https://github.com/marcoserafini2/angular-filemanager-spring-bridge)
