### ISSUE TITLE
Can i use this without installing bower and grunt?

### ISSUE THREAD

**Issue by Kiranrajkathula** [joni2back/angular-filemanager#32]
i have downloaded as zip and kept in my wamp server, edited the handler.php by giving my local host detials on line 123, 124, 125

what next if im not using bower, any help would benefit me in learning and using filemanager!

**Comment by joni2back** [comment]
Hello, bower and grunt are not required if you don't need to modify the javascript sources.

To run the backend handler, you must install the [php-classic](https://github.com/joni2back/php-classic) library at ```angular-filemanager-master/bridges/php/php-classic```

For example: autoload.php should be in the following path
```angular-filemanager-master/bridges/php/php-classic/src/autoloader.php```

Then you could list the files ... Take into account that ```handler.php``` does not include all the operations... its an example file

Dont forget to give us a star!! :star: . Regards!

**Comment by joni2back** [comment]
@Kiranrajkathula Have you solve this issue?
