### ISSUE TITLE
Set authorization header

### ISSUE THREAD

**Issue by SebLeich** [joni2back/angular-filemanager#326]
is it possible to set the authorization header? I use a bearer token and the server needs the following header: "Authorization" "Bearer [token]"

Thank you!

**Comment by morteza-gho** [comment]
In `apihandler.js` file, I add this:

`$http.defaults.headers.common['Authorization'] = 'Bearer ' + token;`

**Comment by durasj** [comment]
I can think of two ways to handle this.

You can either write a $http interceptor or add default headers as @morteza-gho pointed out, but rather in your code.

Or you can proxy the requests through some endpoint on the same domain so you could use cookies.
