### ISSUE TITLE
How to install in a proyect??

### ISSUE THREAD

**Issue by dBer** [joni2back/angular-filemanager#333]
Hello, 

I have a project and I have followed the section "Using in your existing project" but dont`t works.

I have imported all js and css in my html file and have write the tag `<angular-filemanager></angular-filemanager>`

But I think that I must write code in my module, to activate this feature. Can you help me? Is there any specific documentation? I can't get it.

Thanks in advance.

**Comment by SDhalor** [comment]
You need to have an HTML block inside <angular-filemanager></angular-filemanager> which initialises the required controller
