### ISSUE TITLE
Use ng-annotate

### ISSUE THREAD

**Issue by weisk** [joni2back/angular-filemanager#34]
You can get rid of explicit dependency injection array notation, removing a lot of boilerlate code. The module [gulp-ng-annotate](https://www.npmjs.com/package/gulp-ng-annotate) does it automatically for you.

Extra: using wildcard globs to select all files instead of specifying each one.

On your **gulpfile.coffee:**

```javascript
var ngAnnotate = require('gulp-ng-annotate');

gulp.task('concat-uglify-js', function() {
  return gulp.src('assets/js/*.js')
    .pipe(concat('angular-filemanager.min.js'))
    .pipe(ngAnnotate())
    .pipe(uglify())
    .pipe(gulp.dest(dst))
});
```

This will automatically convert all DI functions into array syntax, this way you only have to declare your modules normally:

```javascript
angular.module('FileManagerApp').controller('FileManagerCtrl',
    function($scope, $translate, $cookies, fileManagerConfig, Item, FileNavigator, FileUploader) {
```

**Comment by joni2back** [comment]
Hi @weisk I like the idea to use this wildcard instead of specifying each file.
Regarding ngAnnotate, I'm used to use the dependency injection specifying the name first as string.. 
I prefer to continue this way and prevent to use another gulp plugin...

If its right for you, you can send a pull request with the ```concat-uglify-js``` task wildcard modification..
Thanks!!

**Comment by weisk** [comment]
Gulp plugins are free! They don't increase the library size, just for development :p

As you wish though, I'll make the PR soon.

**Comment by joni2back** [comment]
:+1:  great!

**Comment by joni2back** [comment]
Done at https://github.com/joni2back/angular-filemanager/commit/978039430cc899e4dd9981e78036cd5fd7cc4a43
