### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [joni2back/angular-filemanager#347]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by joni2back** [comment]
Hey! This will be great!!!
Sure.

**Comment by mansya** [comment]
Hi sir, I have design logo for this project. what do you think ? do you like it ? which one do you like it ? let me know if there is something you want to change.
![variation color](https://user-images.githubusercontent.com/33461607/45182396-441f6680-b24b-11e8-8f8d-1791a8904342.png)

**Comment by mansya** [comment]
how about the logo. I really hope for a positive response from you.
