### ISSUE TITLE
/assets/templates/index.html Not found 

### ISSUE THREAD

**Issue by vikaskuppili1** [joni2back/angular-filemanager#35]
hello jonas ,first of i thank you for u r contribution , i am using this on flask framework . so i need keep separate source file in the static folder and html in templates folder upon doing so , i have changed the source file locations and change the location according my source location structure . event though i have changed all  soruce locations it is giving the error  /assets/templates/index.html Not found  

i have checked all of the file which are included .

thanks in advance

**Comment by joni2back** [comment]
Hi @vikaskuppili1 first of all, the templates are compiled in [```dist/cached-templates.js```](https://github.com/joni2back/angular-filemanager/blob/master/dist/cached-templates.js) with ```gulp build``` command.

In the html code, you should view template inclusion like ```<div ng-include="'assets/templates/navbar.html'"></div>``` using ```assets/templates``` as template folder... 

So... if you are going to use other template path you must redefine this new path in these html files...
Then, you must specify this path in the [```gulpfile.js```](https://github.com/joni2back/angular-filemanager/blob/master/gulpfile.js) to make a new template compilation, so... the code will turn to this:
```js
gulp.task('cache-templates', function () {
  return gulp.src(src + 'templates/*.html')
    .pipe(templateCache('cached-templates.js', {
      module: 'FileManagerApp',
      base: function(file) {
        return 'MY/NEW/FOLDER/OF/TEMPLATES' + path.basename(file.history);
      }
    }))
    .pipe(gulp.dest(dst));
});
```
Then you just must run  ```gulp build``` command. 

PD: Don't forget to give a star :star: 

Regards!

**Comment by vikaskuppili1** [comment]
Thank you Very much for u r info i been hitting my head to wall for 4 hours for this . 

and also should i must have to use the gulp for using  this or is it not necessary .
and one more thing is that i hadnt included gulp file in my working project just taken required components then howcome it loaded the gulp file 

please do ignore if i annoy u asking silly question ,  and once again thank you very much

**Comment by joni2back** [comment]
Hey @vikaskuppili1 I made changes in the app, now you only need to define your template directory at [```config.js```](https://github.com/joni2back/angular-filemanager/blob/master/assets/js/config.js)         
```js
 tplPath: 'MY/NEW/PATH'
```
And in [```gulpfile.js```](https://github.com/joni2back/angular-filemanager/blob/master/gulpfile.js)  
```js
var tplPath = 'MY/NEW/PATH' //must be same as fileManagerConfig.tplPath
```
Then run ```gulp build```

**Comment by joni2back** [comment]
If you dont want to use gulp, you should do the following over the index.html main file

```html
  <!-- Uncomment if you need to use raw source code
    <script src="assets/js/app.js"></script>
    <script src="assets/js/config.js"></script>
    <script src="assets/js/chmod.js"></script>
    <script src="assets/js/item.js"></script>
    <script src="assets/js/filenavigator.js"></script>
    <script src="assets/js/fileuploader.js"></script>
    <script src="assets/js/translations.js"></script>
    <script src="assets/js/controller.js"></script>
    <script src="assets/js/selector-controller.js"></script>
  -->
  
  <script src="dist/angular-filemanager.min.js"></script><!-- Comment if you need to use raw source code -->
  <script src="dist/cached-templates.js"></script><!-- Comment if you need to use raw source code -->
```

**Comment by vikaskuppili1** [comment]
hi joni 

 using this 

 <script src="dist/angular-filemanager.min.js"></script>
  <script src="dist/cached-templates.js"></script>

it raising a url problem of POST http://127.0.0.1:5000/bridges/php/handler.php  which i changed in my project

**Comment by vikaskuppili1** [comment]
hii  jonas i have followed it . it is raisng another error 

GET http://127.0.0.1:5000/assets/templates/navbar.html 404 (NOT FOUND)b @ angular.min.js:87m @ angular.min.js:83$get.f @ angular.min.js:80(anonymous function) @ angular.min.js:112$get.l.$eval @ angular.min.js:126$get.l.$digest @ angular.min.js:123$get.l.$apply @ angular.min.js:126l @ angular.min.js:81O @ angular.min.js:86w.onload @ angular.min.js:87
angular.min.js:87 GET http://127.0.0.1:5000/assets/templates/sidebar.html 404 (NOT FOUND)b @ angular.min.js:87m @ angular.min.js:83$get.f @ angular.min.js:80(anonymous function) @ angular.min.js:112$get.l.$eval @ angular.min.js:126$get.l.$digest @ angular.min.js:123$get.l.$apply @ angular.min.js:126l @ angular.min.js:81O @ angular.min.js:86w.onload @ angular.min.js:87
angular.min.js:87 GET http://127.0.0.1:5000/assets/templates/current-folder-breadcrumb.html 404 (NOT FOUND)b @ angular.min.js:87m @ angular.min.js:83$get.f @ angular.min.js:80(anonymous function) @ angular.min.js:112$get.l.$eval @ angular.min.js:126$get.l.$digest @ angular.min.js:123$get.l.$apply @ angular.min.js:126l @ angular.min.js:81O @ angular.min.js:86w.onload @ angular.min.js:87
angular.min.js:87 GET http://127.0.0.1:5000/assets/templates/main-table.html 404 (NOT FOUND)b @ angular.min.js:87m @ angular.min.js:83$get.f @ angular.min.js:80(anonymous function) @ angular.min.js:112$get.l.$eval @ angular.min.js:126$get.l.$digest @ angular.min.js:123$get.l.$apply @ angular.min.js:126l @ angular.min.js:81O @ angular.min.js:86w.onload @ angular.min.js:87
angular.min.js:87 GET http://127.0.0.1:5000/assets/templates/modals.html 404 (NOT FOUND)b @ angular.min.js:87m @ angular.min.js:83$get.f @ angular.min.js:80(anonymous function) @ angular.min.js:112$get.l.$eval @ angular.min.js:126$get.l.$digest @ angular.min.js:123$get.l.$apply @ angular.min.js:126l @ angular.min.js:81O @ angular.min.js:86w.onload @ angular.min.js:87
angular.min.js:87 GET http://127.0.0.1:5000/assets/templates/item-context-menu.html 404 (NOT FOUND)
\

it might be due to u havent assigned the tplPath to every one of the html

**Comment by vikaskuppili1** [comment]
go the solution jonas ,when ever ui uses

<script src="dist/angular-filemanager.min.js"></script>
  <script src="dist/cached-templates.js"></script>

these are becoming cached so clean  the caches  history is  the solution
