### ISSUE TITLE
json structure for directory with in directies,files 

### ISSUE THREAD

**Issue by vikaskuppili1** [joni2back/angular-filemanager#36]
hi joni ,can u please provide  json structure for the representing directories with directories  and files , the nested structer . in your documentation u haven't demonstrated that .

**Comment by vikaskuppili1** [comment]
hey joni plz do reply

**Comment by joni2back** [comment]
Hi @vikaskuppili1 the app does not work with nested directories .. Each request must return the list of files and dirs of the current directory... (Take into account if the nested structure is much deep, the request-response sime could be very long). 

So, the API doc for listing is the following https://github.com/joni2back/angular-filemanager/blob/master/API.md#listing

Regards

**Comment by vikaskuppili1** [comment]
hm okay but where as the example is showing directories with in directories how is that happens

**Comment by vikaskuppili1** [comment]
the tree structure directories containing files

**Comment by vikaskuppili1** [comment]
![angular-filemanager](https://cloud.githubusercontent.com/assets/13166746/8508789/b106c96a-229c-11e5-8c5f-3466b15d55c6.png)


in that it is showing wp-admin ,.... in blog na

**Comment by vikaskuppili1** [comment]
ok got it every request must be list of directories and files of the current directory 

okay then in what way i have to send the json such that it should be sub directory of some other director where should we have to indicate that in json

**Comment by joni2back** [comment]
No one, the tree navigator have a smart piece of code to make that..
https://github.com/joni2back/angular-filemanager/blob/master/assets/js/filenavigator.js#L47
To inspect with developer console, just run 
**angular.element(document.getElementsByTagName('div')[0]).scope().fileNavigator.history**

**Comment by vikaskuppili1** [comment]
sorry can u plz elaborate that

**Comment by vikaskuppili1** [comment]
how it is deciding one folder is subfolder of the other , in order to do that in what way we have pass the json input stating that this is subfolder of that (x) .can be plz given given example json send request example

**Comment by vikaskuppili1** [comment]
if my asked question is total wrong then plz do ignore me but plz provide the sol for my requirement 

example : i have a folder a and folder b which is subset of a and a file f which resides in folder b 
now plz make a json response that it will displayed in the ur ui with hierarchy ..thank you very much

**Comment by vikaskuppili1** [comment]
okay got the solution we have to read the path from the post json data and send the required directories and file of that current directory accordingly 

Thanks
