### ISSUE TITLE
assets/templates not found

### ISSUE THREAD

**Issue by ktamilvanan** [joni2back/angular-filemanager#43]
I have placed the assets/templates at the root of my application. I see an empty page being loaded but no request to the server is sent. 

There is an error on the console, assets/templates/ Failed to load resource: the server responded with a status of 404 (Not Found) but the folder is there. 
![capture](https://cloud.githubusercontent.com/assets/3724506/8558673/e307ca52-24ba-11e5-81e0-1b0b331cf70f.PNG)

**Comment by Vikas-Stormy** [comment]
you have to place that in  frameworks default search for the files . and given that fodler location in you template . if you use gulp then this modifications should be compiled there  also 
feel free to ask ..

**Comment by joni2back** [comment]
Hi @ktamilvanan , to change the templates folder, you need to do the following:

Edit ```assets/js/config.js``` and ```gulpfile.js```, then define the path in ```tplPath``` variable.
The changes should be like this...
```diff
diff --git a/assets/js/config.js b/assets/js/config.js
index e79e536..a57b11f 100644
--- a/assets/js/config.js
+++ b/assets/js/config.js
@@ -35,6 +35,6 @@
         isImageFilePattern: /\.(jpe?g|gif|bmp|png|svg|tiff?)$/i,
         isExtractableFilePattern: /\.(gz|tar|rar|g?zip)$/i,
-        tplPath: 'assets/templates'
+        tplPath: 'NEW/TEMPLATE/PATH'
     });
 })(angular);
diff --git a/gulpfile.js b/gulpfile.js
index 0e4e0d1..5f713b5 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -12,7 +12,7 @@ var path = require('path');
 var src = 'assets/';
 var dst = 'dist/';
-var tplPath = 'assets/templates' //must be same as fileManagerConfig.tplPath
+var tplPath = 'NEW/TEMPLATE/PATH' //must be same as fileManagerConfig.tplPath
```
-----------
So, after that, you must run ```gulp build``` in the console.
