### ISSUE TITLE
update view 

### ISSUE THREAD

**Issue by Vikas-Stormy** [joni2back/angular-filemanager#44]
hello jonas ,i have a requirement that based upon the button click event i just need to refresh the folders i,e 

i have created a function in  FileManagerCtrl
and in that i have called the  $scope.fileNavigator.refresh(); 
it is sending a post request to server fine but it is not updating in the view 

can u plz provide a solution for that 

by example of front end button and the function in FileManagerCtrl

**Comment by joni2back** [comment]
Hello @Vikas-Stormy , can you explain the issue with more details ?
You need to refresh the filelist (right-side) or the folderlist (tree from left-side) ?

**Comment by Vikas-Stormy** [comment]
need to refresh the file list  and folder list both upon clicking a button thank u jonas

**Comment by joni2back** [comment]
Ok, how are you binding the button click event?

**Comment by Vikas-Stormy** [comment]
i have a scope problem jonas i have an another app angular js app ng-flow i need to integrate both of 

can u suggest some tips what need to take care  of when merging both of it .like as they both have the conrtrollers 

when i use FileManagerCtrl outside of the <angular-file-manager i></angular-file-manager> i am getting a scope problem

**Comment by joni2back** [comment]
You could use $rootScope to unify actions of multiple controllers

Another way is to do something like 
```html
<div ng-controller="YourAppCtrl">
  lalala
  <div ng-controller="FileManagerCtrl">
    <button ng-click="fileNavigator.refresh()">Refresh</button>
  </div>
</div>
```

**Comment by Vikas-Stormy** [comment]
thank you jonas u r helping me alot ,i have solved this by using another approach
