### ISSUE TITLE
Web application functionality error with php and vsftpd

### ISSUE THREAD

**Issue by rsx491** [joni2back/angular-filemanager#47]
Multiple issues with all functionality, including relative navigation resolution to general functionality breaking when configured to work with a jailed user and vsftpd. Maybe 30% works. Followed general make instructions including make install.

**Comment by joni2back** [comment]
Hello @rsx491 first of all, handler.php is a simple and unmaintained script to run the demo. 
The idea is to provide a frontend interface, to make your own backend bridge with your requirements.

Btw, can you list/describe the errors?

**Comment by rsx491** [comment]
Just getting the files and folders displayed when the page initially loads. I'm getting no javascript errros, and php handler also fires no errors. There's a request to "handler.php" for params: {mode: "list", onlyFolders: false, path: "/"}, which returns an empty response.

Sorry if my original post seemed .... forward.

**Comment by joni2back** [comment]
Do the following, try with passive mode off in ```handler.php```

```php
$oFtp = new FileManager(array(
    'hostname' => 'site.com',
    'username' => 'site@site.com',
    'password' => 'abc123',
    'passive'  => false //<-- add this
));
```

**Comment by rsx491** [comment]
I literally have the following as my defaults. Any reason why you appended username@sitename on your using name setting? 

    protected $_port      = 21;
    protected $_timeout   = 10;
    protected $_passive   = false;
    protected $_debug     = true;
    protected $_conn   = true;
    protected $_ssl   = false;

**Comment by rsx491** [comment]
I set passive, but it didn't seem to make a difference. Oddly, I'm able to create directories/folders, which show up on my server, but the file upload does not work and no files are displayed in the main tree.

**Comment by joni2back** [comment]
Could be a fatal error..
do the following:
```php

ini_set('display_errors', E_ALL);
error_reporting(E_ALL);
//ExceptionCatcherJSON::register(); //<-- comment this too
$oFtp = new FileManager(array(
    'hostname' => 'dsadsa.com',
    'username' => 'dsaa@dsadsa.com',
    'password' => 'dasdsa',
    'debug' => true,
));

$oFtp->connect();
var_dump($oFtp->listFilesRaw(''));
exit;
```

and look the response with the browser developer tool..

**Comment by rsx491** [comment]
I created a quick script and tried connecting, authenticating, and making directories and uploading files. It's worked so far, so I know my configuration is working.

As for related PHP errors. I'm running a vanilla flavored version, where PHP is included in the web server work tree.

<?php 

ini_set('display_errors',1); 
error_reporting(E_ALL & ~E_NOTICE);

$ftp_server = '127.0.0.1';
$ftp_port = '21';
$ftp_user_name = 'filemanager';
$ftp_user_pass = '123';
$ftp_timeout = '1';
$ftp_dir_path = '/home/filemanager';

$random_dir = function()
{
    $characters = ’0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ’;
    $randstring = '';
    for ($i = 0; $i < 10; $i++) {
        $randstring = $characters[rand(0, strlen($characters))];
    }
    return $randstring;
};

if(!$ftpstream = ftp_connect($ftp_server, $ftp_port, $ftp_timeout)){
	echo "connection not established.<br>";
	var_dump($ftpstream);
}
else{
	echo "connected. continuing.<br>";
}
ftp_pasv ($ftpstream, true) ;
 
$login = ftp_login($ftpstream, $ftp_user_name, $ftp_user_pass);
if($login) {
	echo "we are logged in with '$ftp_user_name'.<br>";
}
else{
	echo "cound not log in with '$ftp_user_name'.<br>";
}

/*
$random_directory = $random_dir();
echo "trying to create dir ./$random_directory.<br>";
$dir_result = ftp_mkdir($ftpstream,  "./$random_directory");

if (!$dir_result) {
	echo "cound not create directory .<br>";
}
else{
	echo "dir created. <br>";
}
*/

// upload a file
if (ftp_put($ftpstream, './readme.txt', 'readme.txt', FTP_ASCII)) {
 echo "successfully uploaded $file\n";
} else {
 echo "There was a problem while uploading $file\n";
}
 
ftp_close($ftpstream);

Output:
connected. continuing.
we are logged in with 'filemanager'.
successfully uploaded

Static and dynamic mods:
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php5_module (shared)
 setenvif_module (shared)
 status_module (shared)

**Comment by rsx491** [comment]
Here's my request payload, using the upload feature. I'm not seeing any new log entries for this file upload request. I am seeing log entries for my quick PHP upload script.

------WebKitFormBoundaryXVKKv2a86j2BrXTP
Content-Disposition: form-data; name="destination"

/
------WebKitFormBoundaryXVKKv2a86j2BrXTP
Content-Disposition: form-data; name="file-1"; filename="invoice_june.csv"
Content-Type: text/csv


------WebKitFormBoundaryXVKKv2a86j2BrXTP--

vsftpd.log log file:
Wed Jul  8 16:22:53 2015 [pid 18730] [filemanager] FTP response: Client "127.0.0.1", "215 UNIX Type: L8"
Wed Jul  8 16:22:53 2015 [pid 18730] [filemanager] FTP command: Client "127.0.0.1", "QUIT"
Wed Jul  8 16:22:53 2015 [pid 18730] [filemanager] FTP response: Client "127.0.0.1", "221 Goodbye."
Wed Jul  8 16:23:36 2015 [pid 18998] CONNECT: Client "127.0.0.1"
Wed Jul  8 16:23:36 2015 [pid 18998] FTP response: Client "127.0.0.1", "220 (vsFTPd 3.0.2)"
Wed Jul  8 16:23:36 2015 [pid 18998] FTP command: Client "127.0.0.1", "PASV"
Wed Jul  8 16:23:36 2015 [pid 18998] FTP response: Client "127.0.0.1", "530 Please login with USER and PASS."
Wed Jul  8 16:23:36 2015 [pid 18998] FTP command: Client "127.0.0.1", "USER filemanager"
Wed Jul  8 16:23:36 2015 [pid 18998] [filemanager] FTP response: Client "127.0.0.1", "331 Please specify the password."
Wed Jul  8 16:23:36 2015 [pid 18998] [filemanager] FTP command: Client "127.0.0.1", "PASS <password>"
Wed Jul  8 16:23:36 2015 [pid 18997] [filemanager] OK LOGIN: Client "127.0.0.1"
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP response: Client "127.0.0.1", "230 Login successful."
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP command: Client "127.0.0.1", "TYPE A"
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP response: Client "127.0.0.1", "200 Switching to ASCII mode."
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP command: Client "127.0.0.1", "PORT 127,0,0,1,224,106"
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP response: Client "127.0.0.1", "200 PORT command successful. Consider using PASV."
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP command: Client "127.0.0.1", "STOR ./readme.txt"
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP response: Client "127.0.0.1", "150 Ok to send data."
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] OK UPLOAD: Client "127.0.0.1", "/./readme.txt", 41 bytes, 109.10Kbyte/sec
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP response: Client "127.0.0.1", "226 Transfer complete."
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP command: Client "127.0.0.1", "QUIT"
Wed Jul  8 16:23:36 2015 [pid 19001] [filemanager] FTP response: Client "127.0.0.1", "221 Goodbye."

**Comment by rsx491** [comment]
It is returning server data, file listing included at the very end.

array(22) { [0]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "D" } [1]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "F" } [2]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "P" } [3]=> array(10) { ["time"]=> string(5) "13:37" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(7) "adfasdf" } [4]=> array(10) { ["time"]=> string(5) "13:22" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(4) "adsf" } [5]=> array(10) { ["time"]=> string(5) "18:43" ["day"]=> string(2) "07" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(8) "asdfasdf" } [6]=> array(10) { ["time"]=> string(5) "13:11" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwxr-xr-x" ["type"]=> string(3) "dir" ["name"]=> string(1) "b" } [7]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "f" } [8]=> array(10) { ["time"]=> string(5) "19:05" ["day"]=> string(2) "07" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(5) "fdfdf" } [9]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "g" } [10]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "h" } [11]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "m" } [12]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "o" } [13]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "5" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(5) "test1" } [14]=> array(10) { ["time"]=> string(5) "15:36" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(10) "test123123" } [15]=> array(10) { ["time"]=> string(5) "13:25" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(9) "test21222" } [16]=> array(10) { ["time"]=> string(5) "13:23" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(6) "test22" } [17]=> array(10) { ["time"]=> string(5) "13:23" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(8) "test2222" } [18]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "y" } [19]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "�" } [20]=> array(10) { ["time"]=> string(5) "13:20" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(4) "4096" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "2" ["rights"]=> string(10) "drwx------" ["type"]=> string(3) "dir" ["name"]=> string(1) "4" } [21]=> array(10) { ["time"]=> string(5) "16:23" ["day"]=> string(2) "08" ["month"]=> string(3) "Jul" ["size"]=> string(2) "41" ["group"]=> string(3) "100" ["user"]=> string(3) "999" ["number"]=> string(1) "1" ["rights"]=> string(10) "-rw-------" ["type"]=> string(4) "file" ["name"]=> string(10) "readme.txt" } }

**Comment by rsx491** [comment]
I have enabled passive mode, as it doesn't seem to matter at this point. Here is the complete handshake when the Filemanager page loads, everything seems to complete successful for reading the FTP root directory.

Wed Jul  8 17:02:32 2015 [pid 24387] CONNECT: Client "127.0.0.1"
Wed Jul  8 17:02:32 2015 [pid 24387] FTP response: Client "127.0.0.1", "220 (vsFTPd 3.0.2)"
Wed Jul  8 17:02:32 2015 [pid 24387] FTP command: Client "127.0.0.1", "USER filemanager"
Wed Jul  8 17:02:32 2015 [pid 24387] [filemanager] FTP response: Client "127.0.0.1", "331 Please specify the password."
Wed Jul  8 17:02:32 2015 [pid 24387] [filemanager] FTP command: Client "127.0.0.1", "PASS <password>"
Wed Jul  8 17:02:32 2015 [pid 24386] [filemanager] OK LOGIN: Client "127.0.0.1"
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP response: Client "127.0.0.1", "230 Login successful."
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP command: Client "127.0.0.1", "PASV"
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP response: Client "127.0.0.1", "227 Entering Passive Mode (127,0,0,1,48,80)."
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP command: Client "127.0.0.1", "TYPE A"
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP response: Client "127.0.0.1", "200 Switching to ASCII mode."
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP command: Client "127.0.0.1", "LIST"
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP response: Client "127.0.0.1", "150 Here comes the directory listing."
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP response: Client "127.0.0.1", "226 Directory send OK."
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP command: Client "127.0.0.1", "SYST"
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP response: Client "127.0.0.1", "215 UNIX Type: L8"
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP command: Client "127.0.0.1", "QUIT"
Wed Jul  8 17:02:32 2015 [pid 24390] [filemanager] FTP response: Client "127.0.0.1", "221 Goodbye."

**Comment by rsx491** [comment]
I worked through the vsfptd configuration again, making a new ftp restricted user. Before the FTP user was able to "chroot" and was reading from the system's root "/", due to the web apps configuration using just "/". So reading and creating directories works. The file upload/download still doesn't work, and there are no related log actions in vsftpd.log.

![headers](https://cloud.githubusercontent.com/assets/4013267/8583906/63c36fae-259f-11e5-8b97-fe72c0907a89.png)
![response](https://cloud.githubusercontent.com/assets/4013267/8583905/63c1ce4c-259f-11e5-85c7-210b8a16a73e.png)

**Comment by joni2back** [comment]
Hello @rsx491 .
For your particular situation, I recommend you to make your own php-bridge from scratch.
There are a lot of libraries that could do the job.. like @Nicolab [php-ftp-client](https://github.com/Nicolab/php-ftp-client) 
or the @touki653 [php-ftp-wrapper](https://github.com//php-ftp-wrapper).

Regards!

**Comment by rsx491** [comment]
Thanks.

There does seem to be an issue with the "fileUploader" JS service. No file information is passed, or accessible from this service. I tried printing out the file information from this service. There was no file data.

(function(window, angular) {
    "use strict";
    angular.module('FileManagerApp').service('fileUploader', ['$http', 'fileManagerConfig', function ($http, fileManagerConfig) {
        var self = this;
        self.requesting = false; 
        self.upload = function(fileList, path, success, error) {
            var form = new window.FormData();
            form.append('destination', '/' + path.join('/'));
            for (var file in fileList) {
                var fileObj = fileList[file];
                typeof fileObj === 'object' && form.append('file-' + (1 + parseInt(file, null)), fileObj);
            }

            self.requesting = true;
            
<--- test -->

            alert("File request");
            alert(JSON.stringify(fileList));
			for (var file in fileList) {
                var fileObj = fileList[file];
                if( typeof fileObj === 'object'){
					alert(JSON.stringify(file));
				}
            } 

<--- test -->
            
            /*
            return $http.post(fileManagerConfig.uploadUrl, form, 
            {
                transformRequest: angular.identity,
                headers: {'Content-Type': undefined}
            }).
            success(function(data) 
            {
                self.requesting = false;
                typeof success === 'function' && success(data);
                alert('success data: ' + data);
            }).
            error(function(data) 
            {
				alert('file failure!');
                self.requesting = false;
                typeof error === 'function' && error(data);
            });
            */
        };
    }]);
})(window, angular);

**Comment by joni2back** [comment]
I will check this.. but.. for example in php you could get the file info(name, size, etc) in $_FILES variable.

**Comment by rsx491** [comment]
I tried capturing the posted values using "php://input", but file related data we returned.
It seems the controller file, using the "fileUploader" service never receives any file data. As
the controller's input of "$scope.uploadFileList" appears to be empty. Has anyone else had this problem?
I've tested in Firefox and Chrome.

**Comment by joni2back** [comment]
Hey @rsx491, take a look to the [updated doc](https://github.com/joni2back/angular-filemanager/blob/master/API.md#upload-file-url-filemanagerconfiguploadurl-method-post-content-type-multipartform-data). There are an example to handle the uploaded file with php
