### ISSUE TITLE
How do i load files (am not using bower)?  Help.

### ISSUE THREAD

**Issue by edtronic** [joni2back/angular-filemanager#50]
I get no error in php or java.

i get this.
![captura de pantalla 2015-07-17 a las 13 33 34](https://cloud.githubusercontent.com/assets/2230082/8755462/444f6f16-2c88-11e5-923d-e68c8cf6abfb.png)

**Comment by edtronic** [comment]
Am no using bower or grunt.

**Comment by edtronic** [comment]
Maby you can giveme an example on how to load.

Thank you for any help.

**Comment by joni2back** [comment]
Hi @edtronic. First of all you need to edit your [handler.php](https://github.com/joni2back/angular-filemanager/blob/master/bridges/php/handler.php) file in order to use your ftp credentials.

Maybe you are getting a php fatal error, check the issue #47

**Comment by edtronic** [comment]
Can i only input information via FTP?

**Comment by joni2back** [comment]
Hola, veo que hablas español.

La idea del filemanager es usar la parte javascript y frontend para asi adaptar tu propio conector en el lenguaje de backend que prefieras, como ser php o python...

Es decir, deberias hacer un controlador que interactue con la API que se indica en la [documentacion](https://github.com/joni2back/angular-filemanager/blob/master/API.md)

Los conectores que se incluyen en el proyecto son solo de demostracion, para hacer funcionar el demo online...

Saludos.

**Comment by edtronic** [comment]
Hola, gracias por respuesta.

Te entiendo y me parece un proyecto genial. Te hago una ultima pregunta.

Como genera/despliega el "filemanager" las vistas automáticamente en el Frontend (en el file tree, i.e las carpetitas) a partir de la informacion que viene del Backend. Cual es el archivo que debería estudiar para llegar a entender ese mecanismo.

Muchas gracias Joni.

**Comment by joni2back** [comment]
Buenas, mira eso lo hace a partir de los archivos que va listando, son funciones recursivas que guardan en una variable de tipo historial las carpetas y sus nodos hijos para asi formar un arbol navegable..
Es decir, se hace automaticamente a medida que se va navegando (no es otro request)

Saludos.

**Comment by edtronic** [comment]
La version del archivo "angula-filemanager.min.js " esta en alguna parte no minificada?

**Comment by joni2back** [comment]
Si te fijas en el codigo html de index.html, muestra una forma de usar la app sin los archivos minificados. es decir, tendrias que incluir uno por uno los archivos sueltos (que es lo que esta comentado) y comentar los minificados!
