### ISSUE TITLE
Configuring the servlet for Java based application

### ISSUE THREAD

**Issue by starspn** [joni2back/angular-filemanager#57]
Good day,

I am trying to setup the servlet to to use it on my java application. I did add the servlet on my web.xml
I can see the serlvet it loading some properties file (angular-filemanager.properties) what should be the contect of the file?

**Comment by joni2back** [comment]
Hello, I add to @paolobiavati (that build the java connector because I dont have experience with java.

Regards.

**Comment by starspn** [comment]
I don't understand what you are saying?

**Comment by joni2back** [comment]
Mmm, I dont understand if you are having troubles with the JAVA connector or the frontend API...

**Comment by starspn** [comment]
Java connector  on the servlet you are defining 

propertiesFile = getClass().getClassLoader().getResourceAsStream("angular-filemanager.properties");

Can you give an example of the content of this file angular-filemanager.properties?

**Comment by joni2back** [comment]
Hi @starspn, I checked the source code, the properties of this file are

```repository.base.url``` and ```date.format```

The format of the file should be compatible with http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html

Please, let me know if work with this, regards.
