### ISSUE TITLE
Please remove me from this project

### ISSUE THREAD

**Issue by sebastianbergmann** [joni2back/angular-filemanager#59]

**Comment by sebastianbergmann** [comment]
Nevermind; recalled how one can remove oneself from a repository.

**Comment by joni2back** [comment]
Sorry there was an error with the username.

**Comment by bartaz** [comment]
not one problem I guess, I just got notification I was added, too

**Comment by fabpot** [comment]
hmmm, I also got the notification

**Comment by joni2back** [comment]
Sorry, just removeds

**Comment by serbanghita** [comment]
I also received the notification ... please remove me
