### ISSUE TITLE
body { overflow: hidden; }

### ISSUE THREAD

**Issue by mohsen1** [joni2back/angular-filemanager#61]
Since both panes have scrolling overflow, you can set overflow of the body to hidden to disable bounce on overscroll on body element
![screen shot 2015-09-15 at 9 06 54 am 2](https://cloud.githubusercontent.com/assets/543633/9882372/24970ee2-5b89-11e5-8323-fb34f7dbc3c6.png)

**Comment by joni2back** [comment]
Hello @mohsen1.
I don't understand at all your suggestion,
The left sidebar is fixed so the right content works with the body scrollbar..

Can you please provide a PR o fork with the fix?

Regards!!!

**Comment by mohsen1** [comment]
I didn't notice you're using body scroll for right pane. The "overscroll" effect drops down the top bar (as seen in screenshot) which is not something user expects. Maybe add height 100% and `scroll: auto` to the right pane and set body overflow to hidden. Please try it in developer tools and if you agreed it's something you want to add I'd be happy to propose a PR

**Comment by joni2back** [comment]
I don't view the same first blank line as your screenshot, what brand and version of browser are you using?
Can you inspect the dom and paste another screenshot of the element that generate that?

Thanks!

**Comment by mohsen1** [comment]
I'm using Mac and Chrome. It's the same with Safari

http://gfycat.com/ValidFatherlyBaiji

**Comment by joni2back** [comment]
Hmmm Im now in ubuntu, this afternoon i'll try with osx.
But if you can, please provide a fix in a PR and I be very interested to merge to the master!
Regards.

**Comment by joni2back** [comment]
Hello @mohsen1, seems like all websites have this behavior on osx browsers...

**Comment by mohsen1** [comment]
I personally don't like it. But it's your call
