### ISSUE TITLE
Clear sidebar tree navigator with unopened folders

### ISSUE THREAD

**Issue by hmartos** [joni2back/angular-filemanager#63]
Hello, I know this bug is marked as closed, but I have noticed that it is only working when you click on a folder that have at least one subfolder.

If you click on a folder that have subfolders then tree navigator opens the folder structure, and if you click on another folder that have subfolders the unused folder structure is closed and the new folder structure is opened properly, but if you click on a folder that do not have any subfolder then the unused folder structure is not closed.

![image](https://cloud.githubusercontent.com/assets/13253656/10162041/8dcb3abc-66a8-11e5-859e-6a2578b3fdb3.png)

![image](https://cloud.githubusercontent.com/assets/13253656/10162070/d53d8aa8-66a8-11e5-84a2-eaaae9cef124.png)

![image](https://cloud.githubusercontent.com/assets/13253656/10162082/e93354f2-66a8-11e5-954a-092f6fd5d408.png)

I have noticed also that the order of the folders shown in sidebar tree navigation is not the same shown in main-table, I have solved this by sorting nodes in lowercase, inside filenavigator -> buildTree

```javascript
parent.nodes = parent.nodes.sort(function(a, b) {
    return a.name.toLowerCase() < b.name.toLowerCase() ? -1 : a.name.toLowerCase() === b.name.toLowerCase() ? 0 : 1;
});
```

Thank you for your time!.

**Comment by joni2back** [comment]
Hello @hmartos yes I'm aware of this bug, and others like renaming folders etc in the sidebar. I want to fix them all doing a refactory in the buildTree method. 

Also I saw the same behaviour in the sort of the folder. Would be great if you want to create a pull request with this fix, in order to collaborate in this project !! :smile:

**Comment by hmartos** [comment]
It is my first pull request, so tell me if I have done something wrong! Thank you very much!

**Comment by joni2back** [comment]
:ok: Done sidebar sort   
:watch: pending sidebar item updates (same with #9)
