### ISSUE TITLE
Errors when using example

### ISSUE THREAD

**Issue by hkong** [joni2back/angular-filemanager#68]
Very excited to try this, but I'm getting errors using the instructions for building the example in the README.md.  Specifically, I'm getting this error in the browser console:

> Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I'm assuming the error is for the app defined in `angular-filemanager/src/js/app.js`, since my minimal HTML has no controllers.  I've tried using Angular 1.3.20 as well as 1.4.7 and get the same error.

**Comment by joni2back** [comment]
Hello @hkong can you paste the entire content of your html file that is including the <angular-filemanager> tag?

**Comment by joni2back** [comment]
Hi again @hkong , problem fixed at 4b01df5a2db5ce9c87da1dd59f79c85103b0cc74!
