### ISSUE TITLE
authenticate, and pass credentials to backend ftp server

### ISSUE THREAD

**Issue by marsbard** [joni2back/angular-filemanager#7]
I was hoping this was going to ask me for credentials and pass them to the backend ftp server but currently it doesn't. This would be a lot more useful than just exposing a single account and having unauthenticated access to it.

In case you're interested, I was hoping to add it to our community build of the alfresco ECM system https://github.com/marsbard/puppet-alfresco to provide a lightweight alternative to the main UI.

**Comment by joni2back** [comment]
Hi Martin, a login page its a good idea that i've forgotten.
To clarify, are you interested to collaborate in this project developing a bridge (backend API) for Alfresco? ..and i can make the login page.

Regards!

**Comment by marsbard** [comment]
Actually I did think that initially but actually Alfresco implements an ftp server so we were thinking to use that, that would be quickest to get it going. We might consider a bridge later as it could give us more fine grained control perhaps.

**Comment by joni2back** [comment]
The idea of this file manager is to be used with multiples purposes, not just as a ftp file navigator.
The scope is determined by the bridge/connector .. for example could be work as a system file navigator.

By the way, i just created an issue #8 that is related with an optional/pre-configurable login section. 
If you are interested to work on it you are welcome proposing a pull request (frontend or backend). 
Thanks!

**Comment by marsbard** [comment]
If we were to make a bridge at some point in the future it would likely be CMIS browser bindings
