### ISSUE TITLE
Drop file anywhere to upload

### ISSUE THREAD

**Issue by durasj** [joni2back/angular-filemanager#73]
The idea is to simplify file uploading. File could be dropped anywhere and would be uploaded. I think it would be best to use project https://github.com/danialfarid/ng-file-upload ... License is the same (MIT) and you will be able to provide a lot of features in practically no time.

Main features copied from their readme:

•file upload progress, cancel/abort
•file drag and drop (html5 only) 
•image paste form clipboard and drag and drop from browser pages (html5 only).
•image resize native and image crop through ngImgCrop. See crop sample (html5 only) 
•resumable uploads: pause/resume upload (html5 only) 
•validation on file type/size, image width/height, video/audio duration and  ng-required  support.
•show thumbnail or preview of selected images/audio/videos

**Comment by joni2back** [comment]
Hello, drag and drop is a feature that should be implemented.
This weeks im on vacations, are you interested to create a pull-request with this changes?
Regards!

**Comment by jlamer** [comment]
Unfortunately, I dont have almost any experience with angular. I think I have knowleadge to do the majority of things in JS, but I am not sure if quality of my code would be sufficient in case I tried to do something for project based on angular. For example I dont know any best practices which you guys follow. Maybe someone else could help.

**Comment by fkoester** [comment]
I will try to implement this in the next days.

**Comment by joni2back** [comment]
Great!! .. Please take into account the related bridge ***click-changes*** that at the moment the actions (requests to the api) of item entity will be migrated to a service in charge of this

**Comment by jlamer** [comment]
I was fiddling with the angular in the past few weeks and I could probably try to code this in the case @fkoester have not already started working on it.

**Comment by fkoester** [comment]
@jlamer I did not start working on it yet, so please go ahead! :+1:

**Comment by jlamer** [comment]
OK, I have some basic example not really using upload functions of module but only some directives.

Please take a look and try it out: #113

**Comment by mamashin** [comment]
Great work !
What about file upload progress ?

**Comment by jlamer** [comment]
I will look at it probably over the weekend. I want to complete integration so the module will be used completedy as it should be but without some advanced features.

**Comment by joni2back** [comment]
The new API docs (beta) are here https://github.com/joni2back/angular-filemanager/blob/click-changes/API.md

**Comment by jlamer** [comment]
Great, that will help me for sure.

**Comment by jlamer** [comment]
I finally had some time to add proper integration of ng-files-upload (including ). Check it please out: https://github.com/jlamer/angular-filemanager/tree/file-upload-v2 ... It won't break compatibility with existing bridges. I tested it with php bridge but it should work with java bridge just fine.
