### ISSUE TITLE
Error decoding cyrillic P symbol

### ISSUE THREAD

**Issue by dntstp** [joni2back/angular-filemanager#75]
if folder contains any file with cyrillic P symbol causes to "Bridge response error"
```
    protected function _buildFileLinux($ftpLine)
    {   
     ...
         $chunks = preg_split("/\s+/", $ftpLine);
```
replacing regexp  worked for me: 
```
        $chunks = preg_split("/ +/", $ftpLine);
```

**Comment by joni2back** [comment]
Great!!, can you create a pull request in [php-classic](https://github.com/joni2back/php-classic) ?
Thanks!!

**Comment by joni2back** [comment]
Fixed!
