### ISSUE TITLE
Question : Does it support multiple instances?

### ISSUE THREAD

**Issue by cyc60** [joni2back/angular-filemanager#78]
Hi. Awesome project!
Can I add two instances of angular-filemanager with different backends to a page.

**Comment by joni2back** [comment]
Yes you can, but you should change your config provider for each instance...
Are you considering to use both in the same window.document ??

**Comment by cyc60** [comment]
Yes.

**Comment by joni2back** [comment]
Not at the moment, but is a good idea !
