### ISSUE TITLE
Brigde Java Upload

### ISSUE THREAD

**Issue by GutoMartins019** [joni2back/angular-filemanager#81]
I tried to use the upload function, but i always get an error, even if file is uploaded correctly.

 My solution is that code on servlet is missing a sucess response. Like i did:

responseJsonObject = success(null);
			response.setContentType("application/json");
			PrintWriter out = response.getWriter();
			out.print(responseJsonObject);
			out.flush();

This is the correct way?

**Comment by joni2back** [comment]
Hello, the java bridge was developed with a github collaborator, can you modify at you own following the api docs!
