### ISSUE TITLE
Bridge response error, please check the docs

### ISSUE THREAD

**Issue by jamiechoi** [joni2back/angular-filemanager#82]
I hosted this using hostinger and got this error. What are the possible reasons and how do I fix it?

**Comment by joni2back** [comment]
Hello @jamiechoi can you look the backend file response?... Did you clone the repo with --recursive param? (in order to include the dependencies of php-classic framework)

**Comment by sagarora77** [comment]
Cloned the github repo with --recursive, removed all the dependencies, using Php bridge for connectivity, still getting the same "Bridge response error". Please suggest some way out.

**Comment by joni2back** [comment]
Hi @sagarora77 Are you using another angular lib/framework that performs the requests to the backend bridge?

**Comment by sagarora77** [comment]
Hi @joni2back ,
No, I am not using any framework, just trying to implement it in localhost with valid ftp credentials and verified it with FileZilla. Having classic php handler in place. Need your help to figure out the exact problem.

**Comment by boloindia** [comment]
Hi @sagarora77 Better install apache server xampp or wamp with Filezilla which will execute the code in handler.php

**Comment by joni2back** [comment]
@sagarora77 @boloindia Of course you need to use also a php web server to run the ftp-connection handler :smile:

**Comment by sagarora77** [comment]
Thanks man for the support!

I solved the issue, the port number was the issue with my server.

Warmest regard

Sagar Arora

On Fri, Feb 5, 2016 at 6:11 PM, Jonas Sciangula Street <
notifications@github.com> wrote:

> @sagarora77 <https://github.com/sagarora77> @boloindia
> <https://github.com/boloindia> Of course you need to use also a php web
> server to run the ftp-connection handler [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joni2back/angular-filemanager/issues/82#issuecomment-180336743>
> .
>



-- 
Warm regards,
Sagar Arora

**Comment by sachendrapal** [comment]
@joni2back I am getting the same error as well. As suggested by you, what exact values i need to put into config.js.

**Comment by itdotnet** [comment]
hi
I also have a problem. I have the following error
Error 405 - Bridge response error, please check the API docs or this ajax response

In your opinion, what's the problem?!

**Comment by sachendrapal** [comment]
@itdotnet 
1) Edit your index.html file by adding things,
<script type="text/javascript">
    //example to override angular-filemanager default config
    angular.module('FileManagerApp').config(['fileManagerConfigProvider', function (config) {
      var defaults = config.$get();
      config.set({
        appName: 'Document Management System',
          //appName: 'angular-filemanager',
        pickCallback: function(item) {
          var msg = 'Picked %s "%s" for external use'
            .replace('%s', item.type)
            .replace('%s', item.fullPath());
          window.alert(msg);
        },

        allowedActions: angular.extend(defaults.allowedActions, {
          pickFiles: false,
          pickFolders: false,
        }),
		
		listUrl: 'bridges/php-local/',
		uploadUrl: 'bridges/php-local/',
		renameUrl: 'bridges/php-local/',
		copyUrl: 'bridges/php-local/',
		moveUrl: 'bridges/php-local/',
		removeUrl: 'bridges/php-local/',
		editUrl: 'bridges/php-local/',
		getContentUrl: 'bridges/php-local/',
		createFolderUrl: 'bridges/php-local/',
		downloadFileUrl: 'bridges/php-local/',
		downloadMultipleUrl: 'bridges/php-local/',
		compressUrl: 'bridges/php-local/',
		extractUrl: 'bridges/php-local/',
		permissionsUrl: 'bridges/php-local/',
      });

2) Edit index.php file under php-local to set where you want to store or play with documents locally
$fileManagerApi = new FileManagerApi('../../storage','en');
3) run it through a server. I am running it like by going to the project's root directory and running command
C:\wamp64\bin\php\php7.0.0\php.exe -S localhost:8000

Hope it helps :)

**Comment by itdotnet** [comment]
@sachendrapal 
what things?!
I thank you for your help

**Comment by joni2back** [comment]
Hi @itdotnet  
Are you using a backend server to have a connector for the filemanager?
Please, open your browser developer tools, and let do a screenshot in the ajax response...

**Comment by itdotnet** [comment]
hi @joni2back 
i just used script files As mentioned in the documentation in visual studio and I run the project.
I have attached the output you

**Comment by itdotnet** [comment]
![capture](https://cloud.githubusercontent.com/assets/20128916/16378140/5c7b1dd0-3c7f-11e6-86b8-679122c51046.JPG)

In addition, error in the FileZila to be shown

**Comment by joni2back** [comment]
Hi, seems dont have the backend running well..

Are you really using an apache/nginx server..?

**Comment by itdotnet** [comment]
my project run in visual studio. how to i use apache server?!
I start Apache on xampp. but i dont know how to sync the two together.
apache service port changed my desired Because it was interfering.

**Comment by joni2back** [comment]
@itdotnet If you have installed PHP, you can open a console in angular-filemanager folder then run
```php -S0.0.0.0:8000```

**Comment by peastuti** [comment]
I'm having a 500 internal server error. I edited /bridges/php/includes/Ftp.php.
Angular-Filemanager runs on my debian server with apache2 server at https://ws.peastuti.com/angular-filemanager/ with this config

   ```
 protected $_hostname  = 'peastuti.asuscomm.com/shares/folder/';
    protected $_username  = '------';
    protected $_password  = '------';
    protected $_port      = 21;
    protected $_timeout   = 90;
    protected $_passive   = true;
    protected $_debug     = false;
    protected $_conn   = false;
    protected $_ssl   = false;
```

**Comment by joni2back** [comment]
Hi @peastuti , could you give the php error log for this error 500?
you could add this in the ftp.php code

error_reporting(E_ALL); ini_set('display_errors', E_ALL);

**Comment by peastuti** [comment]
Nothing happens, here a screenshot
<img width="1228" alt="schermata 2016-08-01 alle 15 18 31" src="https://cloud.githubusercontent.com/assets/18187660/17295227/5f2936e2-57fb-11e6-903d-5d6eaac1b658.png">

**Comment by joni2back** [comment]
@peastuti You should check the PHP error_log of this server in order to know that error...

**Comment by peastuti** [comment]
`[Mon Aug 01 13:39:48.648549 2016] [:error] [pid 25283] [client 181.90.121.159:10121] PHP Fatal error:  Class 'AngularFilemanager\\LocalBridge\\stream' not found in /var/www/ws.peastuti.com/public_html/angular-filemanager/bridges/php-local/LocalBridge/Rest.php on line 167
[Mon Aug 01 13:39:54.421605 2016] [:error] [pid 25202] [client 181.90.121.159:10122] PHP Notice:  Undefined index: action in /var/www/ws.peastuti.com/public_html/angular-filemanager/bridges/php-local/LocalBridge/FileManagerApi.php on line 171
[Mon Aug 01 13:43:02.291250 2016] [:error] [pid 24798] [client 79.19.107.37:64439] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Invalid connection' in /var/www/ws.peastuti.com/public_html/angular-filemanager/bridges/php/includes/Ftp.php:114\nStack trace:\n#0 /var/www/ws.peastuti.com/public_html/angular-filemanager/bridges/php/includes/Ftp.php(544): PHPClassic\\Ftp->_isConnected()\n#1 /var/www/ws.peastuti.com/public_html/angular-filemanager/bridges/php/includes/Ftp.php(561): PHPClassic\\Ftp->close()\n#2 [internal function]: PHPClassic\\Ftp->__destruct()\n#3 {main}\n  thrown in /var/www/ws.peastuti.com/public_html/angular-filemanager/bridges/php/includes/Ftp.php on line 114, referer: https://ws.peastuti.com/angular-filemanager/
`

**Comment by itdotnet** [comment]
I've received this error now:
Error 200 - Bridge response error, please check the API docs or this ajax response

**Comment by ztigr** [comment]
Hi,
I'm getting the same error on 000webhost, but I noticed when I took out the width and height specifications from my css statement, the error went away?

**Comment by groschatchauve** [comment]
I had the same problem when using WAMP PHP version and I resolve it by setting up an original version of PHP from the official website. Don't forget to update the Path environment variable which include the PHP folder you want to use.

**Comment by vancuf** [comment]
Getting the same Error 405, in developer mode in the browser on line 99 in angular.min.js getting this error "Failed to load resource: the server responded with a status of 405 (Method Not Allowed)" how do i fix it?
