### ISSUE TITLE
Suggestion: Change how the server API is integrated

### ISSUE THREAD

**Issue by iJungleboy** [joni2back/angular-filemanager#83]
The current implementation seems to do the following:

1. expect a config file to define the api endpoints `/src/js/providers/config.js`
2. assume that a standard json will be handled by the server
3. have an object-oriented item-approach on `/src/js/entities/item.js` which then has various actions like move, copy, etc.

This has quite a few drawbacks IMHO which would probably be easy to fix with a different setup. For example, we use a CMS called DNN which has its own web API - but doesn't match this API. Parameters are different etc. And if I would like to use a "static" server - basically a bunch of pre-rendered JSONs to just quickly run the UI, do some tests and maybe use it as the prototype for the next implementation of a bridge, then this is basically impossible. 

My suggestion is to

1. create an angular service in charge of the server commands. let's call it `serverbridge.js` or `webapi.js`
2. this would contain commands like `list(...)`, `copy(...)` etc. each returning the promise to a json-data package just like the system expects. the bridge must handle errors etc.

Why bother?
Basically this would allow us to create different bridges for each server implementation. This would allow things like

* a fake bridge returning a list of folders/files which never talks to the server, great for testing and playing with the tool
* bridges which talk to already existing APIs, which would convert returned data into the expected format without having to re-create the server side
* bridges which have more intelligence regarding the server. For example, certain server implementations expect security tokens (hashed keys) to be added to each request, or some bridges may need to get an initial configuration (allow files, etc.) while others don't need that

So that's my suggestion. I'm not fully sure yet how bridge-swapping would work - if this is a gulp-build thing to then create different compiles with different bridges, or if it would be configurable. 

What do you guys think?

**Comment by deardooley** [comment]
I agree. That's what we had to do in our case. We use a generic service backend and swapped out the existing api calls for appropriate callbacks to that. In our case we found we needed to reimplement both fileitem and permission to support a non Unix permission model. 

if you want to rewrite the url dynamically to provide deep linking, then you may need to hack the directory tree controller to properly respond to things like updir requests when the root of the tree isn't actually '/'.

**Comment by joni2back** [comment]
Hi @iJungleboy @deardooley Im working on part of this at ***[click-changes](https://github.com/joni2back/angular-filemanager/tree/click-changes)*** branch.
This is an api refactor and a api-service in the js side (in order to support multiple files)

**Comment by joni2back** [comment]
Hi again @iJungleboy  @deardooley I took your suggestion
Take a look to:

* https://github.com/joni2back/angular-filemanager/blob/click-changes/src/js/services/apimiddleware.js [converts any model data and executes the method in the request-handler]
* https://github.com/joni2back/angular-filemanager/blob/click-changes/src/js/services/apihandler.js [do the request to the backend]

**Comment by iJungleboy** [comment]
Very cool :+1:

**Comment by deardooley** [comment]
well played, sir. +1
