### ISSUE TITLE
No effect.

### ISSUE THREAD

**Issue by VijaySankhat** [joni2back/angular-filemanager#85]
I did all the things as given, but not able to see anything. I mean it does not shows anything at front, can you guide me please

**Comment by joni2back** [comment]
Hello @VijaySankhat can you see if there are any error in your javascript console? Thanks

**Comment by VijaySankhat** [comment]
No, not any error on javascript console I already seen there.

**Comment by joni2back** [comment]
Do you have any modifications in the project?

**Comment by VijaySankhat** [comment]
No still not

**Comment by joni2back** [comment]
Let me try...

**Comment by VijaySankhat** [comment]
When I run your source separately from browser then it runs fine.

**Comment by joni2back** [comment]
the php source?

**Comment by VijaySankhat** [comment]
No I mean UI

**Comment by VijaySankhat** [comment]
I want to use your filemanager in my own module so how should I add dependency?

**Comment by joni2back** [comment]
Did you fork the project with
$ git clone https://github.com/joni2back/angular-filemanager.git --recursive

**Comment by VijaySankhat** [comment]
I just download your module from git-source and then simply run it.

**Comment by VijaySankhat** [comment]
I have this kind of code. check this.
<code>
var app =  angular
  .module('MY_OWN_MODULE', [
    
  ]).config(['fileManagerConfigProvider', function (config) {
    var defaults = config.$get();
    config.set({
      appName: 'my angular-filemanager',
      allowedActions: angular.extend(defaults.allowedActions, {
        remove: true
      })
    });
  }]);</code>

**Comment by joni2back** [comment]
Nope, you must use ***FileManagerApp*** instead of ***MY_OWN_MODULE*** to extend the config

**Comment by VijaySankhat** [comment]
Then Would I be able to use this on "MY_OWN_MODULE" template page??

**Comment by VijaySankhat** [comment]
Then would I be able to call file manager from "MY_OWN_MODULE" template?

**Comment by joni2back** [comment]
Yes, you need to use angular-filemanager in another page (maybe an iframe)
Or just use 2 different angular apps in the same dom...
