### ISSUE TITLE
logout support

### ISSUE THREAD

**Issue by kernel164** [joni2back/angular-filemanager#89]
my backend https://github.com/kernel164/gofe needs a logout button. It would be cool to have one.

Sample Config:
```
logoutUrl: '/logout',
```

if logoutUrl not present - don't show logout button at top right
if logoutUrl present - show logout button

**Comment by fkoester** [comment]
Hi @kernel164 . I have a similar requirement for my project. I need a logout button but also at least one extra button for getting to the "manage users" function of my app.

So I think the proper solution is not to directly provide a logout button (and maybe more buttons for feature xy) in this project but rather allow to integrate the angular-filemanager UI component into your own project.

I created a pull request for the required changes here: https://github.com/joni2back/angular-filemanager/pull/107

**Comment by joni2back** [comment]
Great... I guess the best approach to this issue is to let angular-filemanager be used as wrapped element and have a logout link offside of the filemanager.. what do you think? @kernel164 @fkoester

**Comment by jlamer** [comment]
I don't think something like authentication should be part of filemanager. It should only be part of something bigger. Or am I missing something?

**Comment by joni2back** [comment]
logout url not should be part of angular-filemanager regarding the pull-request of @fkoester .
Thanks!
