### ISSUE TITLE
File Delete and Co-responding Tree View in Left Navigation Bar

### ISSUE THREAD

**Issue by mandatorySuicide** [joni2back/angular-filemanager#9]
When a directory is deleted , the left side menu's tree view should be updated as well. But it doesn't happen automatically. I used your module somewhere in my project and I had to update your "buildTree" method to update the left navigation tree when a directory is deleted. I think you should fix it in your project as well ASAP. :)

**Comment by joni2back** [comment]
Hello, I just created an issue with this bug. If you found a solution, please don't forget make a pull request.
Regards.

**Comment by joni2back** [comment]
If you are using this project, please don't forget to give a star :yum:

**Comment by mandatorySuicide** [comment]
Ya I already fixed it :) Right now I am rebuilding the whole tree after
querying my server but I am looking for a better approach. Tomorrow I have
to close my sprint and that's why I am running out of time with my project
but as soon as I get some time I will work with it. I am also planning some
enhancement to add drag and drop file upload. I mean i want to enhance your
file upload feature. Your code is very nice and your documentation was
awesome. But I am just a beginner , i write very ugly code. As soon as I
make my updates I will give you my code and you just review my code and
make the necessary update. :)

Regards,
Najim Ahmed



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=najim.ju@gmail.com&idSignature=22>

**Comment by joni2back** [comment]
Excellent :+1: !!!

**Comment by mandatorySuicide** [comment]
Hey, I just fixed the issue! It works nicely with asp .net Web API backend!


Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=najim.ju@gmail.com&idSignature=22>

**Comment by joni2back** [comment]
great!! can you please make a pull request?

**Comment by mandatorySuicide** [comment]
Yes, hopefully today or tomorrow I will make a pull request :) yesterday I
just learned how to fork and send pull request :p .

**Comment by joni2back** [comment]
Ok, if you have problems doing the pull request, just paste the code here :smile_cat:

**Comment by mandatorySuicide** [comment]
Hi , Please check if you got my pull request with my updated code.



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=najim.ju@gmail.com&idSignature=22>

**Comment by Vikas-Stormy** [comment]
jonas fix this issue its not fixed yet .

**Comment by ishakya** [comment]
I am also having issue with this. Please solve as soon as possible.

**Comment by joni2back** [comment]
Hi @ishakya, I am aware of this bug, I'm considering to rewrite the method that the sidebar tree works.

**Comment by joni2back** [comment]
Already fixed !!! https://github.com/joni2back/angular-filemanager/pull/77
