### ISSUE TITLE
Unknown error creating this folder

### ISSUE THREAD

**Issue by pvasanth0506** [joni2back/angular-filemanager#90]
i am working localhost...
{"result":{"success":false,"error":"Unknown error creating this folder","errorDetail":{"type":"Exception" ,"code":0}}} this error coming

**Comment by joni2back** [comment]
Hi @pvasanth0506, can you please first check if you can create a folder via ftp software like FileZilla?
Seems like are permission problems...

**Comment by pvasanth0506** [comment]
i am working in linux OS....now i am getting  permission in  root folder...then
this type of error in console
POST http://localhost/angular-filemanager-master/bridges/php/handler.php
	
500 Internal Server Error

![screenshot from 2015-12-22 10 00 35](https://cloud.githubusercontent.com/assets/16303410/11948055/56ca23d2-a895-11e5-9c4d-a1513cf34e6f.png)

**Comment by pvasanth0506** [comment]
Is it possible to work in localhost??

**Comment by joni2back** [comment]
Yes, but you need to configure your handler.php file to set your ftp credentials...
So, to ensure that works fine, first test with filezilla if you can connect to the same ftp account and create a folder.

**Comment by pvasanth0506** [comment]
hai,,,
i want this type of file manager....
plz send the localhost  working file manager....
i cannot understand file manager whole file.....
tell me the file flow  sir
thank u

**Comment by joni2back** [comment]
You need to debug your backend php connector or ftp credentials in order to verify if you are able to create folders regarding ftp permissions or something like that.
regards!

**Comment by pvasanth0506** [comment]
thank u sir,,,i ll try further enquiry text u later
