### ISSUE TITLE
Cannot connect to the FTP server

### ISSUE THREAD

**Issue by zackgtr** [joni2back/angular-filemanager#92]
Hola, he configurado el archivo handler.php con los datos de mi servidor FTP pero aun así me dice que no puedo conectar con el servidor, tampoco me permite crear carpetas, subir archivos, ni nada. Podrías ayudarme?

**Comment by joni2back** [comment]
Hola, pudiste verificar con FileZilla u otro gestor de ftp que las credenciales sean validas?
Si de todas maneras tenes problema, fijate de conectarte a ftp sin modo pasivo, es decir...

```php
$oFtp = new FileManager(array(
    'hostname' => '',
    'username' => '',
    'password' => '',
    'passive' => false
));
```

**Comment by acze** [comment]
I got same response: "Cannot connect to the FTP server".
I filled $oFtp array with correct FTP account details.
```
$oFtp = new FileManager(array(
    'hostname' => 'localhost',
    'username' => 'user',
    'password' => 'password'
));
```
What im doing wrong?
