### ISSUE TITLE
PHP Bridge code for working demo

### ISSUE THREAD

**Issue by ssnukala** [joni2back/angular-filemanager#97]
Thanks for the plugin. This is very helpful.

Do you have working PHP code that is on your demo site, which shows the image preview and also create directory etc. the current php code says 
throw new \Exception('This action is not available in the demo');
I am particularly interested in the image preview, for me it is opening the image in a separate window, but your demo shows it as a modal popup

Would be great if you can post the updated code, I am using the SRC files as i have some custom requirements

Srinivas

**Comment by joni2back** [comment]
Hi @ssnukala now in config settings you can enable or disable the image preview in modals.
So, you can extend the config to do something like:

```html
<script type="text/javascript">
//example to override angular-filemanager default config
angular.module('FileManagerApp').config(['fileManagerConfigProvider', function (config) {
  config.set({
    previewImagesInModal: false
  });
}]);
</script>
````
