### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by zhouxh** [joni2back/angular-filemanager#98]
is this not  useful in win10? when open  with file   thow error “ Invalid chmod input data”

**Comment by zhouxh** [comment]
That's because the returned array name is empty. Thus parsing “chmod” when the error occurred.I added a filter function on it.
 function delEmpty($v)   
{  
	if ($v['name']===null || $v['name']==="")   //当数组name为null,或者为空的时候删除改元素
		return false;  
	}  
	return true;  
}  
 $list = array_filter($list,"delEmpty");

**Comment by zhouxh** [comment]
The above that there is a mistake, after the serial number to delete the chaos, I re modified the next, only the first element to deal with.
 if($list[0]['name']===null||$list[0]['name']==='')
   {
	   array_splice($list, 0, 1);
   }

**Comment by joni2back** [comment]
Hi.... let me check in a ftp server thru windows.
Btw, if you pass an empty value in ```rights``` response property, should work fine.
After it, you can disable the permissions in frontend extending the config file

**Comment by zhouxh** [comment]
thanks  !
